; NOTE: Assertions have been autogenerated by test/update_tpde_llc_test_checks.py UTC_ARGS: --version 5
; SPDX-FileCopyrightText: 2025 Contributors to TPDE <https://tpde.org>
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

; RUN: tpde-llc --target=x86_64 %s | %objdump | FileCheck %s -check-prefixes=X64

define x86_fp80 @ret0() {
; X64-LABEL: <ret0>:
; X64:         fldz
; X64-NEXT:    ret
  ret x86_fp80 0xK00000000000000000000
}

define x86_fp80 @ret1() {
; X64-LABEL: <ret1>:
; X64:         fld1
; X64-NEXT:    ret
  ret x86_fp80 0xK3FFF8000000000000000
}

define x86_fp80 @ret2() {
; X64-LABEL: <ret2>:
; X64:         fld tbyte ptr <ret1+0xf>
; X64-NEXT:     R_X86_64_PC32 -0x4
; X64-NEXT:    ret
  ret x86_fp80 0xK3FEB8637BD05AF6C69B6
}

define x86_fp80 @arg_ret(x86_fp80 %p) {
; X64-LABEL: <arg_ret>:
; X64:         push rbp
; X64-NEXT:    mov rbp, rsp
; X64-NEXT:    fld tbyte ptr [rbp + 0x10]
; X64-NEXT:    pop rbp
; X64-NEXT:    ret
  ret x86_fp80 %p
}

define x86_fp80 @call_ret() {
; X64-LABEL: <call_ret>:
; X64:         push rbp
; X64-NEXT:    mov rbp, rsp
; X64-NEXT:    sub rsp, 0x40
; X64-NEXT:  <L0>:
; X64-NEXT:    call <L0>
; X64-NEXT:     R_X86_64_PLT32 ret0-0x4
; X64-NEXT:    fstp tbyte ptr [rbp - 0x40]
; X64-NEXT:    fld tbyte ptr [rbp - 0x40]
; X64-NEXT:    add rsp, 0x40
; X64-NEXT:    pop rbp
; X64-NEXT:    ret
  %r = call x86_fp80 @ret0()
  ret x86_fp80 %r
}

define void @call_args(x86_fp80 %a, x86_fp80 %b) {
; X64-LABEL: <call_args>:
; X64:         push rbp
; X64-NEXT:    mov rbp, rsp
; X64-NEXT:    sub rsp, 0x50
; X64-NEXT:    movaps xmm0, xmmword ptr <call_args+0x7>
; X64-NEXT:     R_X86_64_PC32 -0x4
; X64-NEXT:    movdqa xmmword ptr [rsp], xmm0
; X64-NEXT:    movapd xmm0, xmmword ptr [rbp + 0x10]
; X64-NEXT:    movdqa xmmword ptr [rsp + 0x10], xmm0
; X64-NEXT:  <L0>:
; X64-NEXT:    call <L0>
; X64-NEXT:     R_X86_64_PLT32 call_args-0x4
; X64-NEXT:    add rsp, 0x50
; X64-NEXT:    pop rbp
; X64-NEXT:    ret
  call void @call_args(x86_fp80 0xK3FFF8000000000000000, x86_fp80 %a)
  ret void
}

define x86_fp80 @load_ret(ptr %p) {
; X64-LABEL: <load_ret>:
; X64:         push rbp
; X64-NEXT:    mov rbp, rsp
; X64-NEXT:    fld tbyte ptr [rdi]
; X64-NEXT:    fstp tbyte ptr [rbp - 0x40]
; X64-NEXT:    fld tbyte ptr [rbp - 0x40]
; X64-NEXT:    pop rbp
; X64-NEXT:    ret
  %l = load x86_fp80, ptr %p
  ret x86_fp80 %l
}

define void @load_store(ptr %p, ptr %q) {
; X64-LABEL: <load_store>:
; X64:         push rbp
; X64-NEXT:    mov rbp, rsp
; X64-NEXT:    fld tbyte ptr [rdi]
; X64-NEXT:    fstp tbyte ptr [rbp - 0x40]
; X64-NEXT:    fld tbyte ptr [rbp - 0x40]
; X64-NEXT:    fstp tbyte ptr [rsi]
; X64-NEXT:    pop rbp
; X64-NEXT:    ret
  %l = load x86_fp80, ptr %p
  store x86_fp80 %l, ptr %q
  ret void
}

define void @load_store_agg(ptr %p, ptr %q) {
; X64-LABEL: <load_store_agg>:
; X64:         push rbp
; X64-NEXT:    mov rbp, rsp
; X64-NEXT:    fld tbyte ptr [rdi]
; X64-NEXT:    fstp tbyte ptr [rbp - 0x70]
; X64-NEXT:    mov rax, qword ptr [rdi + 0x10]
; X64-NEXT:    movss xmm0, dword ptr [rdi + 0x18]
; X64-NEXT:    lea rcx, [rdi + 0x20]
; X64-NEXT:    fld tbyte ptr [rcx]
; X64-NEXT:    fstp tbyte ptr [rbp - 0x40]
; X64-NEXT:    fld tbyte ptr [rbp - 0x70]
; X64-NEXT:    fstp tbyte ptr [rsi]
; X64-NEXT:    mov qword ptr [rsi + 0x10], rax
; X64-NEXT:    movss dword ptr [rsi + 0x18], xmm0
; X64-NEXT:    fld tbyte ptr [rbp - 0x40]
; X64-NEXT:    lea rax, [rsi + 0x20]
; X64-NEXT:    fstp tbyte ptr [rax]
; X64-NEXT:    pop rbp
; X64-NEXT:    ret
  %l = load {x86_fp80, i64, float, x86_fp80}, ptr %p
  store {x86_fp80, i64, float, x86_fp80} %l, ptr %q
  ret void
}

define void @store_const(ptr %p) {
; X64-LABEL: <store_const>:
; X64:         fld1
; X64-NEXT:    fstp tbyte ptr [rdi]
; X64-NEXT:    ret
  store x86_fp80 0xK3FFF8000000000000000, ptr %p
  ret void
}
