; NOTE: Assertions have been autogenerated by test/update_tpde_llc_test_checks.py UTC_ARGS: --version 5
; SPDX-FileCopyrightText: 2025 Contributors to TPDE <https://tpde.org>
;
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

; RUN: tpde-llc --target=x86_64 %s | %objdump | FileCheck %s -check-prefixes=X64
; RUN: tpde-llc --target=aarch64 %s | %objdump | FileCheck %s -check-prefixes=ARM64

declare ptr @llvm.stacksave.p0()
declare void @llvm.stackrestore.p0(ptr)

define void @test() {
; X64-LABEL: <test>:
; X64:         mov rax, rsp
; X64-NEXT:    mov rsp, rax
; X64-NEXT:    ret
;
; ARM64-LABEL: <test>:
; ARM64:         mov x0, sp
; ARM64-NEXT:    mov sp, x0
; ARM64-NEXT:    ret
entry:
  %0 = call ptr @llvm.stacksave.p0()
  call void @llvm.stackrestore.p0(ptr %0)
  ret void
}
