; NOTE: Assertions have been autogenerated by test/update_tpde_llc_test_checks.py UTC_ARGS: --version 5
; SPDX-FileCopyrightText: 2025 Contributors to TPDE <https://tpde.org>
;
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

; RUN: tpde-llc --target=x86_64 %s | %objdump | FileCheck %s -check-prefixes=X64
; RUN: tpde-llc --target=aarch64 %s | %objdump | FileCheck %s -check-prefixes=ARM64

declare void @llvm.prefetch.p0(ptr nocapture readonly, i32 immarg, i32 immarg, i32 immarg)

define void @prefetch_read_local0_inst(ptr %0) {
; X64-LABEL: <prefetch_read_local0_inst>:
; X64:         prefetchnta byte ptr [rdi]
; X64-NEXT:    ret
;
; ARM64-LABEL: <prefetch_read_local0_inst>:
; ARM64:         prfm pldl1strm, [x0]
; ARM64-NEXT:    ret
  entry:
    call void @llvm.prefetch.p0(ptr %0, i32 0, i32 0, i32 0)
    ret void
}

define void @prefetch_read_local1_inst(ptr %0) {
; X64-LABEL: <prefetch_read_local1_inst>:
; X64:         prefetcht2 byte ptr [rdi]
; X64-NEXT:    ret
;
; ARM64-LABEL: <prefetch_read_local1_inst>:
; ARM64:         prfm pldl3keep, [x0]
; ARM64-NEXT:    ret
  entry:
    call void @llvm.prefetch.p0(ptr %0, i32 0, i32 1, i32 0)
    ret void
}

define void @prefetch_read_local2_inst(ptr %0) {
; X64-LABEL: <prefetch_read_local2_inst>:
; X64:         prefetcht1 byte ptr [rdi]
; X64-NEXT:    ret
;
; ARM64-LABEL: <prefetch_read_local2_inst>:
; ARM64:         prfm pldl2keep, [x0]
; ARM64-NEXT:    ret
  entry:
    call void @llvm.prefetch.p0(ptr %0, i32 0, i32 2, i32 0)
    ret void
}

define void @prefetch_read_local3_inst(ptr %0) {
; X64-LABEL: <prefetch_read_local3_inst>:
; X64:         prefetcht0 byte ptr [rdi]
; X64-NEXT:    ret
;
; ARM64-LABEL: <prefetch_read_local3_inst>:
; ARM64:         prfm pldl1keep, [x0]
; ARM64-NEXT:    ret
  entry:
    call void @llvm.prefetch.p0(ptr %0, i32 0, i32 3, i32 0)
    ret void
}

define void @prefetch_write_local0_inst(ptr %0) {
; X64-LABEL: <prefetch_write_local0_inst>:
; X64:         prefetchnta byte ptr [rdi]
; X64-NEXT:    ret
;
; ARM64-LABEL: <prefetch_write_local0_inst>:
; ARM64:         prfm pstl1strm, [x0]
; ARM64-NEXT:    ret
  entry:
    call void @llvm.prefetch.p0(ptr %0, i32 1, i32 0, i32 0)
    ret void
}

define void @prefetch_write_local1_inst(ptr %0) {
; X64-LABEL: <prefetch_write_local1_inst>:
; X64:         prefetcht2 byte ptr [rdi]
; X64-NEXT:    ret
;
; ARM64-LABEL: <prefetch_write_local1_inst>:
; ARM64:         prfm pstl3keep, [x0]
; ARM64-NEXT:    ret
  entry:
    call void @llvm.prefetch.p0(ptr %0, i32 1, i32 1, i32 0)
    ret void
}

define void @prefetch_write_local2_inst(ptr %0) {
; X64-LABEL: <prefetch_write_local2_inst>:
; X64:         prefetcht1 byte ptr [rdi]
; X64-NEXT:    ret
;
; ARM64-LABEL: <prefetch_write_local2_inst>:
; ARM64:         prfm pstl2keep, [x0]
; ARM64-NEXT:    ret
  entry:
    call void @llvm.prefetch.p0(ptr %0, i32 1, i32 2, i32 0)
    ret void
}

define void @prefetch_write_local3_inst(ptr %0) {
; X64-LABEL: <prefetch_write_local3_inst>:
; X64:         prefetcht0 byte ptr [rdi]
; X64-NEXT:    ret
;
; ARM64-LABEL: <prefetch_write_local3_inst>:
; ARM64:         prfm pstl1keep, [x0]
; ARM64-NEXT:    ret
  entry:
    call void @llvm.prefetch.p0(ptr %0, i32 1, i32 3, i32 0)
    ret void
}



define void @prefetch_read_local0_data(ptr %0) {
; X64-LABEL: <prefetch_read_local0_data>:
; X64:         prefetchnta byte ptr [rdi]
; X64-NEXT:    ret
;
; ARM64-LABEL: <prefetch_read_local0_data>:
; ARM64:         prfm pldl1strm, [x0]
; ARM64-NEXT:    ret
  entry:
    call void @llvm.prefetch.p0(ptr %0, i32 0, i32 0, i32 1)
    ret void
}

define void @prefetch_read_local1_data(ptr %0) {
; X64-LABEL: <prefetch_read_local1_data>:
; X64:         prefetcht2 byte ptr [rdi]
; X64-NEXT:    ret
;
; ARM64-LABEL: <prefetch_read_local1_data>:
; ARM64:         prfm pldl3keep, [x0]
; ARM64-NEXT:    ret
  entry:
    call void @llvm.prefetch.p0(ptr %0, i32 0, i32 1, i32 1)
    ret void
}

define void @prefetch_read_local2_data(ptr %0) {
; X64-LABEL: <prefetch_read_local2_data>:
; X64:         prefetcht1 byte ptr [rdi]
; X64-NEXT:    ret
;
; ARM64-LABEL: <prefetch_read_local2_data>:
; ARM64:         prfm pldl2keep, [x0]
; ARM64-NEXT:    ret
  entry:
    call void @llvm.prefetch.p0(ptr %0, i32 0, i32 2, i32 1)
    ret void
}

define void @prefetch_read_local3_data(ptr %0) {
; X64-LABEL: <prefetch_read_local3_data>:
; X64:         prefetcht0 byte ptr [rdi]
; X64-NEXT:    ret
;
; ARM64-LABEL: <prefetch_read_local3_data>:
; ARM64:         prfm pldl1keep, [x0]
; ARM64-NEXT:    ret
  entry:
    call void @llvm.prefetch.p0(ptr %0, i32 0, i32 3, i32 1)
    ret void
}


define void @prefetch_write_local0_data(ptr %0) {
; X64-LABEL: <prefetch_write_local0_data>:
; X64:         prefetchnta byte ptr [rdi]
; X64-NEXT:    ret
;
; ARM64-LABEL: <prefetch_write_local0_data>:
; ARM64:         prfm pstl1strm, [x0]
; ARM64-NEXT:    ret
  entry:
    call void @llvm.prefetch.p0(ptr %0, i32 1, i32 0, i32 1)
    ret void
}

define void @prefetch_write_local1_data(ptr %0) {
; X64-LABEL: <prefetch_write_local1_data>:
; X64:         prefetcht2 byte ptr [rdi]
; X64-NEXT:    ret
;
; ARM64-LABEL: <prefetch_write_local1_data>:
; ARM64:         prfm pstl3keep, [x0]
; ARM64-NEXT:    ret
  entry:
    call void @llvm.prefetch.p0(ptr %0, i32 1, i32 1, i32 1)
    ret void
}

define void @prefetch_write_local2_data(ptr %0) {
; X64-LABEL: <prefetch_write_local2_data>:
; X64:         prefetcht1 byte ptr [rdi]
; X64-NEXT:    ret
;
; ARM64-LABEL: <prefetch_write_local2_data>:
; ARM64:         prfm pstl2keep, [x0]
; ARM64-NEXT:    ret
  entry:
    call void @llvm.prefetch.p0(ptr %0, i32 1, i32 2, i32 1)
    ret void
}

define void @prefetch_write_local3_data(ptr %0) {
; X64-LABEL: <prefetch_write_local3_data>:
; X64:         prefetcht0 byte ptr [rdi]
; X64-NEXT:    ret
;
; ARM64-LABEL: <prefetch_write_local3_data>:
; ARM64:         prfm pstl1keep, [x0]
; ARM64-NEXT:    ret
  entry:
    call void @llvm.prefetch.p0(ptr %0, i32 1, i32 3, i32 1)
    ret void
}
