; NOTE: Assertions have been autogenerated by test/update_tpde_llc_test_checks.py UTC_ARGS: --version 5
; SPDX-FileCopyrightText: 2025 Contributors to TPDE <https://tpde.org>
;
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

; RUN: tpde-llc --target=x86_64 %s | %objdump | FileCheck %s -check-prefixes=X64
; RUN: tpde-llc --target=aarch64 %s | %objdump | FileCheck %s -check-prefixes=ARM64

declare void @llvm.trap()

define void @test() {
; X64-LABEL: <test>:
; X64:         ud2
; X64-NEXT:    ret
;
; ARM64-LABEL: <test>:
; ARM64:         brk #0x1
; ARM64-NEXT:    ret
entry:
    call void @llvm.trap()
    ret void
}
