; NOTE: Assertions have been autogenerated by test/update_tpde_llc_test_checks.py UTC_ARGS: --version 5
; SPDX-FileCopyrightText: 2025 Contributors to TPDE <https://tpde.org>
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

; RUN: tpde-llc --target=x86_64 %s | %objdump | FileCheck %s -check-prefixes=X64
; RUN: tpde-llc --target=aarch64 %s | %objdump | FileCheck %s -check-prefixes=ARM64

define void @store_v1i8(ptr %p) {
; X64-LABEL: <store_v1i8>:
; X64:         mov byte ptr [rdi], 0x7b
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v1i8>:
; ARM64:         mov x1, #0x7b // =123
; ARM64-NEXT:    strb w1, [x0]
; ARM64-NEXT:    ret
  store <1 x i8> <i8 123>, ptr %p
  ret void
}

define void @store_v1i16(ptr %p) {
; X64-LABEL: <store_v1i16>:
; X64:         mov word ptr [rdi], 0x7b
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v1i16>:
; ARM64:         mov x1, #0x7b // =123
; ARM64-NEXT:    strh w1, [x0]
; ARM64-NEXT:    ret
  store <1 x i16> <i16 123>, ptr %p
  ret void
}

define void @store_v1i32(ptr %p) {
; X64-LABEL: <store_v1i32>:
; X64:         mov dword ptr [rdi], 0x7b
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v1i32>:
; ARM64:         mov x1, #0x7b // =123
; ARM64-NEXT:    str w1, [x0]
; ARM64-NEXT:    ret
  store <1 x i32> <i32 123>, ptr %p
  ret void
}

define void @store_v1i64(ptr %p) {
; X64-LABEL: <store_v1i64>:
; X64:         mov qword ptr [rdi], 0x7b
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v1i64>:
; ARM64:         mov x1, #0x7b // =123
; ARM64-NEXT:    str x1, [x0]
; ARM64-NEXT:    ret
  store <1 x i64> <i64 123>, ptr %p
  ret void
}

define void @store_v1ptr(ptr %p) {
; X64-LABEL: <store_v1ptr>:
; X64:         mov qword ptr [rdi], 0x0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v1ptr>:
; ARM64:         mov w1, #0x0 // =0
; ARM64-NEXT:    str x1, [x0]
; ARM64-NEXT:    ret
  store <1 x ptr> <ptr null>, ptr %p
  ret void
}

define void @store_v1f32(ptr %p) {
; X64-LABEL: <store_v1f32>:
; X64:         mov eax, 0x42800000
; X64-NEXT:    movd xmm0, eax
; X64-NEXT:    movss dword ptr [rdi], xmm0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v1f32>:
; ARM64:         mov x16, #0x42800000 // =1115684864
; ARM64-NEXT:    fmov s0, w16
; ARM64-NEXT:    str s0, [x0]
; ARM64-NEXT:    ret
  store <1 x float> <float 64.0>, ptr %p
  ret void
}

define void @store_v1f64(ptr %p) {
; X64-LABEL: <store_v1f64>:
; X64:         movabs rax, 0x4050000000000000
; X64-NEXT:    movq xmm0, rax
; X64-NEXT:    movsd qword ptr [rdi], xmm0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v1f64>:
; ARM64:         mov x16, #0x4050000000000000 // =4634204016564240384
; ARM64-NEXT:    fmov d0, x16
; ARM64-NEXT:    str d0, [x0]
; ARM64-NEXT:    ret
  store <1 x double> <double 64.0>, ptr %p
  ret void
}

define void @store_v2i8(ptr %p) {
; X64-LABEL: <store_v2i8>:
; X64:         mov byte ptr [rdi], 0x7b
; X64-NEXT:    mov byte ptr [rdi + 0x1], 0xc
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v2i8>:
; ARM64:         mov x1, #0x7b // =123
; ARM64-NEXT:    strb w1, [x0]
; ARM64-NEXT:    mov x1, #0xc // =12
; ARM64-NEXT:    strb w1, [x0, #0x1]
; ARM64-NEXT:    ret
  store <2 x i8> <i8 123, i8 12>, ptr %p
  ret void
}

define void @store_v2i16(ptr %p) {
; X64-LABEL: <store_v2i16>:
; X64:         mov word ptr [rdi], 0x7b
; X64-NEXT:    mov word ptr [rdi + 0x2], 0xc
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v2i16>:
; ARM64:         mov x1, #0x7b // =123
; ARM64-NEXT:    strh w1, [x0]
; ARM64-NEXT:    mov x1, #0xc // =12
; ARM64-NEXT:    strh w1, [x0, #0x2]
; ARM64-NEXT:    ret
  store <2 x i16> <i16 123, i16 12>, ptr %p
  ret void
}

define void @store_v2i32(ptr %p) {
; X64-LABEL: <store_v2i32>:
; X64:         movabs rax, 0xc0000007b
; X64-NEXT:    movq xmm0, rax
; X64-NEXT:    movsd qword ptr [rdi], xmm0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v2i32>:
; ARM64:         mov x16, #0x7b // =123
; ARM64-NEXT:    movk x16, #0xc, lsl #32
; ARM64-NEXT:    fmov d0, x16
; ARM64-NEXT:    str d0, [x0]
; ARM64-NEXT:    ret
  store <2 x i32> <i32 123, i32 12>, ptr %p
  ret void
}

define void @store_v2i64(ptr %p) {
; X64-LABEL: <store_v2i64>:
; X64:         movaps xmm0, xmmword ptr <store_v2i32+0x1f>
; X64-NEXT:     R_X86_64_PC32 -0x4
; X64-NEXT:    movups xmmword ptr [rdi], xmm0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v2i64>:
; ARM64:         adrp x16, 0x0 <store_v1i8>
; ARM64-NEXT:     R_AARCH64_ADR_PREL_PG_HI21
; ARM64-NEXT:    ldr q0, [x16]
; ARM64-NEXT:     R_AARCH64_LDST128_ABS_LO12_NC
; ARM64-NEXT:    str q0, [x0]
; ARM64-NEXT:    ret
  store <2 x i64> <i64 123, i64 12>, ptr %p
  ret void
}

define void @store_v2ptr(ptr %p) {
; X64-LABEL: <store_v2ptr>:
; X64:         pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi], xmm0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v2ptr>:
; ARM64:         movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0]
; ARM64-NEXT:    ret
  store <2 x ptr> <ptr null, ptr null>, ptr %p
  ret void
}

define void @store_v2f32(ptr %p) {
; X64-LABEL: <store_v2f32>:
; X64:         movabs rax, 0x4280000042800000
; X64-NEXT:    movq xmm0, rax
; X64-NEXT:    movsd qword ptr [rdi], xmm0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v2f32>:
; ARM64:         mov x16, #0x42800000 // =1115684864
; ARM64-NEXT:    movk x16, #0x4280, lsl #48
; ARM64-NEXT:    fmov d0, x16
; ARM64-NEXT:    str d0, [x0]
; ARM64-NEXT:    ret
  store <2 x float> <float 64.0, float 64.0>, ptr %p
  ret void
}

define void @store_v2f64(ptr %p) {
; X64-LABEL: <store_v2f64>:
; X64:         movaps xmm0, xmmword ptr <store_v2f32+0x1f>
; X64-NEXT:     R_X86_64_PC32 -0x4
; X64-NEXT:    movups xmmword ptr [rdi], xmm0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v2f64>:
; ARM64:         adrp x16, 0x0 <store_v1i8>
; ARM64-NEXT:     R_AARCH64_ADR_PREL_PG_HI21
; ARM64-NEXT:    ldr q0, [x16]
; ARM64-NEXT:     R_AARCH64_LDST128_ABS_LO12_NC
; ARM64-NEXT:    str q0, [x0]
; ARM64-NEXT:    ret
  store <2 x double> <double 64.0, double 64.0>, ptr %p
  ret void
}

define void @store_v3i8(ptr %p) {
; X64-LABEL: <store_v3i8>:
; X64:         mov byte ptr [rdi], 0x0
; X64-NEXT:    mov byte ptr [rdi + 0x1], 0x0
; X64-NEXT:    mov byte ptr [rdi + 0x2], 0x0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v3i8>:
; ARM64:         mov w1, #0x0 // =0
; ARM64-NEXT:    strb w1, [x0]
; ARM64-NEXT:    mov w1, #0x0 // =0
; ARM64-NEXT:    strb w1, [x0, #0x1]
; ARM64-NEXT:    mov w1, #0x0 // =0
; ARM64-NEXT:    strb w1, [x0, #0x2]
; ARM64-NEXT:    ret
  store <3 x i8> zeroinitializer, ptr %p
  ret void
}

define void @store_v3i16(ptr %p) {
; X64-LABEL: <store_v3i16>:
; X64:         mov word ptr [rdi], 0x0
; X64-NEXT:    mov word ptr [rdi + 0x2], 0x0
; X64-NEXT:    mov word ptr [rdi + 0x4], 0x0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v3i16>:
; ARM64:         mov w1, #0x0 // =0
; ARM64-NEXT:    strh w1, [x0]
; ARM64-NEXT:    mov w1, #0x0 // =0
; ARM64-NEXT:    strh w1, [x0, #0x2]
; ARM64-NEXT:    mov w1, #0x0 // =0
; ARM64-NEXT:    strh w1, [x0, #0x4]
; ARM64-NEXT:    ret
  store <3 x i16> zeroinitializer, ptr %p
  ret void
}

define void @store_v3i32(ptr %p) {
; X64-LABEL: <store_v3i32>:
; X64:         mov dword ptr [rdi], 0x0
; X64-NEXT:    mov dword ptr [rdi + 0x4], 0x0
; X64-NEXT:    mov dword ptr [rdi + 0x8], 0x0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v3i32>:
; ARM64:         mov w1, #0x0 // =0
; ARM64-NEXT:    str w1, [x0]
; ARM64-NEXT:    mov w1, #0x0 // =0
; ARM64-NEXT:    str w1, [x0, #0x4]
; ARM64-NEXT:    mov w1, #0x0 // =0
; ARM64-NEXT:    str w1, [x0, #0x8]
; ARM64-NEXT:    ret
  store <3 x i32> zeroinitializer, ptr %p
  ret void
}

define void @store_v3i64(ptr %p) {
; X64-LABEL: <store_v3i64>:
; X64:         mov qword ptr [rdi], 0x0
; X64-NEXT:    mov qword ptr [rdi + 0x8], 0x0
; X64-NEXT:    mov qword ptr [rdi + 0x10], 0x0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v3i64>:
; ARM64:         mov w1, #0x0 // =0
; ARM64-NEXT:    str x1, [x0]
; ARM64-NEXT:    mov w1, #0x0 // =0
; ARM64-NEXT:    str x1, [x0, #0x8]
; ARM64-NEXT:    mov w1, #0x0 // =0
; ARM64-NEXT:    str x1, [x0, #0x10]
; ARM64-NEXT:    ret
  store <3 x i64> zeroinitializer, ptr %p
  ret void
}

define void @store_v3ptr(ptr %p) {
; X64-LABEL: <store_v3ptr>:
; X64:         mov qword ptr [rdi], 0x0
; X64-NEXT:    mov qword ptr [rdi + 0x8], 0x0
; X64-NEXT:    mov qword ptr [rdi + 0x10], 0x0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v3ptr>:
; ARM64:         mov w1, #0x0 // =0
; ARM64-NEXT:    str x1, [x0]
; ARM64-NEXT:    mov w1, #0x0 // =0
; ARM64-NEXT:    str x1, [x0, #0x8]
; ARM64-NEXT:    mov w1, #0x0 // =0
; ARM64-NEXT:    str x1, [x0, #0x10]
; ARM64-NEXT:    ret
  store <3 x ptr> zeroinitializer, ptr %p
  ret void
}

define void @store_v3f32(ptr %p) {
; X64-LABEL: <store_v3f32>:
; X64:         pxor xmm0, xmm0
; X64-NEXT:    movss dword ptr [rdi], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movss dword ptr [rdi + 0x4], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movss dword ptr [rdi + 0x8], xmm0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v3f32>:
; ARM64:         movi v0.8b, #0x0
; ARM64-NEXT:    str s0, [x0]
; ARM64-NEXT:    movi v0.8b, #0x0
; ARM64-NEXT:    str s0, [x0, #0x4]
; ARM64-NEXT:    movi v0.8b, #0x0
; ARM64-NEXT:    str s0, [x0, #0x8]
; ARM64-NEXT:    ret
  store <3 x float> zeroinitializer, ptr %p
  ret void
}

define void @store_v3f64(ptr %p) {
; X64-LABEL: <store_v3f64>:
; X64:         pxor xmm0, xmm0
; X64-NEXT:    movsd qword ptr [rdi], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movsd qword ptr [rdi + 0x8], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movsd qword ptr [rdi + 0x10], xmm0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v3f64>:
; ARM64:         movi v0.8b, #0x0
; ARM64-NEXT:    str d0, [x0]
; ARM64-NEXT:    movi v0.8b, #0x0
; ARM64-NEXT:    str d0, [x0, #0x8]
; ARM64-NEXT:    movi v0.8b, #0x0
; ARM64-NEXT:    str d0, [x0, #0x10]
; ARM64-NEXT:    ret
  store <3 x double> zeroinitializer, ptr %p
  ret void
}

define void @store_v4i8(ptr %p) {
; X64-LABEL: <store_v4i8>:
; X64:         mov byte ptr [rdi], 0x0
; X64-NEXT:    mov byte ptr [rdi + 0x1], 0x0
; X64-NEXT:    mov byte ptr [rdi + 0x2], 0x0
; X64-NEXT:    mov byte ptr [rdi + 0x3], 0x0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v4i8>:
; ARM64:         mov w1, #0x0 // =0
; ARM64-NEXT:    strb w1, [x0]
; ARM64-NEXT:    mov w1, #0x0 // =0
; ARM64-NEXT:    strb w1, [x0, #0x1]
; ARM64-NEXT:    mov w1, #0x0 // =0
; ARM64-NEXT:    strb w1, [x0, #0x2]
; ARM64-NEXT:    mov w1, #0x0 // =0
; ARM64-NEXT:    strb w1, [x0, #0x3]
; ARM64-NEXT:    ret
  store <4 x i8> zeroinitializer, ptr %p
  ret void
}

define void @store_v4i16(ptr %p) {
; X64-LABEL: <store_v4i16>:
; X64:         pxor xmm0, xmm0
; X64-NEXT:    movsd qword ptr [rdi], xmm0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v4i16>:
; ARM64:         movi v0.8b, #0x0
; ARM64-NEXT:    str d0, [x0]
; ARM64-NEXT:    ret
  store <4 x i16> zeroinitializer, ptr %p
  ret void
}

define void @store_v4i32(ptr %p) {
; X64-LABEL: <store_v4i32>:
; X64:         pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi], xmm0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v4i32>:
; ARM64:         movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0]
; ARM64-NEXT:    ret
  store <4 x i32> zeroinitializer, ptr %p
  ret void
}

define void @store_v4i64(ptr %p) {
; X64-LABEL: <store_v4i64>:
; X64:         pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x10], xmm0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v4i64>:
; ARM64:         movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x10]
; ARM64-NEXT:    ret
  store <4 x i64> zeroinitializer, ptr %p
  ret void
}

define void @store_v4ptr(ptr %p) {
; X64-LABEL: <store_v4ptr>:
; X64:         pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x10], xmm0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v4ptr>:
; ARM64:         movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x10]
; ARM64-NEXT:    ret
  store <4 x ptr> zeroinitializer, ptr %p
  ret void
}

define void @store_v4f32(ptr %p) {
; X64-LABEL: <store_v4f32>:
; X64:         pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi], xmm0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v4f32>:
; ARM64:         movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0]
; ARM64-NEXT:    ret
  store <4 x float> zeroinitializer, ptr %p
  ret void
}

define void @store_v4f64(ptr %p) {
; X64-LABEL: <store_v4f64>:
; X64:         pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x10], xmm0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v4f64>:
; ARM64:         movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x10]
; ARM64-NEXT:    ret
  store <4 x double> zeroinitializer, ptr %p
  ret void
}

define void @store_v64i8(ptr %p) {
; X64-LABEL: <store_v64i8>:
; X64:         pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x10], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x20], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x30], xmm0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v64i8>:
; ARM64:         movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x10]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x20]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x30]
; ARM64-NEXT:    ret
  store <64 x i8> zeroinitializer, ptr %p
  ret void
}

define void @store_v64i16(ptr %p) {
; X64-LABEL: <store_v64i16>:
; X64:         pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x10], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x20], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x30], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x40], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x50], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x60], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x70], xmm0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v64i16>:
; ARM64:         movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x10]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x20]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x30]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x40]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x50]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x60]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x70]
; ARM64-NEXT:    ret
  store <64 x i16> zeroinitializer, ptr %p
  ret void
}

define void @store_v64i32(ptr %p) {
; X64-LABEL: <store_v64i32>:
; X64:         pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x10], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x20], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x30], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x40], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x50], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x60], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x70], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x80], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x90], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xa0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xb0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xc0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xd0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xe0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xf0], xmm0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v64i32>:
; ARM64:         movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x10]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x20]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x30]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x40]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x50]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x60]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x70]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x80]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x90]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xa0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xb0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xc0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xd0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xe0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xf0]
; ARM64-NEXT:    ret
  store <64 x i32> zeroinitializer, ptr %p
  ret void
}

define void @store_v64i64(ptr %p) {
; X64-LABEL: <store_v64i64>:
; X64:         pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x10], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x20], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x30], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x40], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x50], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x60], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x70], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x80], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x90], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xa0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xb0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xc0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xd0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xe0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xf0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x100], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x110], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x120], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x130], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x140], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x150], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x160], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x170], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x180], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x190], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x1a0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x1b0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x1c0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x1d0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x1e0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x1f0], xmm0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v64i64>:
; ARM64:         movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x10]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x20]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x30]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x40]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x50]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x60]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x70]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x80]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x90]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xa0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xb0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xc0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xd0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xe0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xf0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x100]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x110]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x120]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x130]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x140]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x150]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x160]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x170]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x180]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x190]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x1a0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x1b0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x1c0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x1d0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x1e0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x1f0]
; ARM64-NEXT:    ret
  store <64 x i64> zeroinitializer, ptr %p
  ret void
}

define void @store_v64ptr(ptr %p) {
; X64-LABEL: <store_v64ptr>:
; X64:         pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x10], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x20], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x30], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x40], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x50], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x60], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x70], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x80], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x90], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xa0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xb0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xc0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xd0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xe0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xf0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x100], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x110], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x120], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x130], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x140], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x150], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x160], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x170], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x180], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x190], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x1a0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x1b0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x1c0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x1d0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x1e0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x1f0], xmm0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v64ptr>:
; ARM64:         movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x10]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x20]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x30]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x40]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x50]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x60]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x70]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x80]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x90]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xa0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xb0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xc0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xd0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xe0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xf0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x100]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x110]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x120]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x130]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x140]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x150]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x160]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x170]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x180]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x190]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x1a0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x1b0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x1c0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x1d0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x1e0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x1f0]
; ARM64-NEXT:    ret
  store <64 x ptr> zeroinitializer, ptr %p
  ret void
}

define void @store_v64f32(ptr %p) {
; X64-LABEL: <store_v64f32>:
; X64:         pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x10], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x20], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x30], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x40], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x50], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x60], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x70], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x80], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x90], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xa0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xb0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xc0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xd0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xe0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xf0], xmm0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v64f32>:
; ARM64:         movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x10]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x20]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x30]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x40]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x50]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x60]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x70]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x80]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x90]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xa0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xb0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xc0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xd0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xe0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xf0]
; ARM64-NEXT:    ret
  store <64 x float> zeroinitializer, ptr %p
  ret void
}

define void @store_v64f64(ptr %p) {
; X64-LABEL: <store_v64f64>:
; X64:         pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x10], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x20], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x30], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x40], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x50], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x60], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x70], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x80], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x90], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xa0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xb0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xc0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xd0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xe0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0xf0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x100], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x110], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x120], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x130], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x140], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x150], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x160], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x170], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x180], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x190], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x1a0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x1b0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x1c0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x1d0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x1e0], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movups xmmword ptr [rdi + 0x1f0], xmm0
; X64-NEXT:    ret
;
; ARM64-LABEL: <store_v64f64>:
; ARM64:         movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x10]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x20]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x30]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x40]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x50]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x60]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x70]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x80]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x90]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xa0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xb0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xc0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xd0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xe0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0xf0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x100]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x110]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x120]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x130]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x140]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x150]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x160]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x170]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x180]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x190]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x1a0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x1b0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x1c0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x1d0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x1e0]
; ARM64-NEXT:    movi v0.16b, #0x0
; ARM64-NEXT:    str q0, [x0, #0x1f0]
; ARM64-NEXT:    ret
  store <64 x double> zeroinitializer, ptr %p
  ret void
}
