; NOTE: Assertions have been autogenerated by test/update_tpde_llc_test_checks.py UTC_ARGS: --version 5
; SPDX-FileCopyrightText: 2025 Contributors to TPDE <https://tpde.org>
;
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

; RUN: tpde-llc --target=x86_64 %s | llvm-objdump -d -r --symbolize-operands --x86-asm-syntax=intel - | FileCheck %s -check-prefixes=X64
; RUN: tpde-llc --target=aarch64 %s | %objdump | FileCheck %s -check-prefixes=ARM64

define i32 @empty_switch(i32 %0) {
; X64-LABEL: <empty_switch>:
; X64:         0: 55 push rbp
; X64-NEXT:    1: 48 89 e5 mov rbp, rsp
; X64-NEXT:    4: e9 00 00 00 00 jmp <L0>
; X64-NEXT:  <L0>:
; X64-NEXT:    9: e9 00 00 00 00 jmp <L1>
; X64-NEXT:  <L1>:
; X64-NEXT:    e: b8 ff ff ff ff mov eax, 0xffffffff
; X64-NEXT:    13: 5d pop rbp
; X64-NEXT:    14: c3 ret
; X64-NEXT:    15: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    1e: 66 90 nop
;
; ARM64-LABEL: <empty_switch>:
; ARM64:         stp x29, x30, [sp, #-0xa0]!
; ARM64-NEXT:    mov x29, sp
; ARM64-NEXT:    b 0xc <empty_switch+0xc>
; ARM64-NEXT:    b 0x10 <empty_switch+0x10>
; ARM64-NEXT:    mov x0, #0xffffffff // =4294967295
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
entry:
  switch i32 %0, label %default []
default:
  ret i32 -1
}

define i32 @basic_switch(i32 %0) {
; X64-LABEL: <basic_switch>:
; X64:         20: 55 push rbp
; X64-NEXT:    21: 48 89 e5 mov rbp, rsp
; X64-NEXT:    24: 83 ff 00 cmp edi, 0x0
; X64-NEXT:    27: 0f 84 1c 00 00 00 je <L0>
; X64-NEXT:    2d: 83 ff 01 cmp edi, 0x1
; X64-NEXT:    30: 0f 84 27 00 00 00 je <L1>
; X64-NEXT:    36: 83 ff 02 cmp edi, 0x2
; X64-NEXT:    39: 0f 84 35 00 00 00 je <L2>
; X64-NEXT:    3f: e9 00 00 00 00 jmp <L3>
; X64-NEXT:  <L3>:
; X64-NEXT:    44: e9 42 00 00 00 jmp <L4>
; X64-NEXT:  <L0>:
; X64-NEXT:    49: 31 c0 xor eax, eax
; X64-NEXT:    4b: 5d pop rbp
; X64-NEXT:    4c: c3 ret
; X64-NEXT:    4d: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    56: 0f 1f 80 00 00 00 00 nop dword ptr [rax]
; X64-NEXT:  <L1>:
; X64-NEXT:    5d: b8 01 00 00 00 mov eax, 0x1
; X64-NEXT:    62: 5d pop rbp
; X64-NEXT:    63: c3 ret
; X64-NEXT:    64: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    6d: 0f 1f 80 00 00 00 00 nop dword ptr [rax]
; X64-NEXT:  <L2>:
; X64-NEXT:    74: b8 02 00 00 00 mov eax, 0x2
; X64-NEXT:    79: 5d pop rbp
; X64-NEXT:    7a: c3 ret
; X64-NEXT:    7b: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    84: 0f 1f 80 00 00 00 00 nop dword ptr [rax]
; X64-NEXT:  <L4>:
; X64-NEXT:    8b: b8 ff ff ff ff mov eax, 0xffffffff
; X64-NEXT:    90: 5d pop rbp
; X64-NEXT:    91: c3 ret
; X64-NEXT:    92: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    9b: 0f 1f 44 00 00 nop dword ptr [rax + rax]
;
; ARM64-LABEL: <basic_switch>:
; ARM64:         stp x29, x30, [sp, #-0xa0]!
; ARM64-NEXT:    mov x29, sp
; ARM64-NEXT:    cmp w0, #0x0
; ARM64-NEXT:    b.eq 0x48 <basic_switch+0x28>
; ARM64-NEXT:    cmp w0, #0x1
; ARM64-NEXT:    b.eq 0x7c <basic_switch+0x5c>
; ARM64-NEXT:    cmp w0, #0x2
; ARM64-NEXT:    b.eq 0xb0 <basic_switch+0x90>
; ARM64-NEXT:    b 0x44 <basic_switch+0x24>
; ARM64-NEXT:    b 0xe4 <basic_switch+0xc4>
; ARM64-NEXT:    mov w0, #0x0 // =0
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov x0, #0x1 // =1
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov x0, #0x2 // =2
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov x0, #0xffffffff // =4294967295
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
entry:
  switch i32 %0, label %default [ i32 0, label %eq0
                                  i32 1, label %eq1
                                  i32 2, label %eq2]
eq0:
  ret i32 0
eq1:
  ret i32 1
eq2:
  ret i32 2
default:
  ret i32 -1
}

define i32 @switch_table(i32 %0) {
; x64-label: switch_table>:
; x64:    b0: 55 push rbp
; x64:    b1: 48 89 e5 mov rbp, rsp
; x64:    b4: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; x64:    bd: 48 81 ec 10 00 00 00 sub rsp, 0x10
; x64:    c4: 83 ff 06 cmp edi, 0x6
; x64:    c7: 0f 87 2f 00 00 00 ja <l0>
; x64:    cd: 89 ff mov edi, edi
; x64:    cf: 48 8d 05 0a 00 00 00 lea rax, <switch_table+0x30>
; x64:    d6: 48 63 3c b8 movsxd rdi, dword ptr [rax + 4*rdi]
; x64:    da: 48 01 f8 add rax, rdi
; x64:    dd: ff e0 jmp rax
; x64:    df: 00 21 add byte ptr [rcx], ah
; x64:    e1: 00 00 add byte ptr [rax], al
; x64:    e3: 00 26 add byte ptr [rsi], ah
; x64:    e5: 00 00 add byte ptr [rax], al
; x64:    e7: 00 2b add byte ptr [rbx], ch
; x64:    e9: 00 00 add byte ptr [rax], al
; x64:    eb: 00 1c 00 add byte ptr [rax + rax], bl
; x64:    ee: 00 00 add byte ptr [rax], al
; x64:    f0: 30 00 xor byte ptr [rax], al
; x64:    f2: 00 00 add byte ptr [rax], al
; x64:    f4: 35 00 00 00 3a xor eax, 0x3a000000
; x64:    f9: 00 00 add byte ptr [rax], al
; x64:    fb: 00 e9 add cl, ch
; x64:    fd: a8 00 test al, 0x0
; x64:    ff: 00 00 add byte ptr [rax], al
; x64:    101: e9 19 00 00 00 jmp <l1>
; x64:    106: e9 2b 00 00 00 jmp <l2>
; x64:    10b: e9 3d 00 00 00 jmp <l3>
; x64:    110: e9 4f 00 00 00 jmp <l4>
; x64:    115: e9 61 00 00 00 jmp <l5>
; x64:    11a: e9 73 00 00 00 jmp <l6>
; x64:  <l1>:
; x64:    11f: b8 00 00 00 00 mov eax, 0x0
; x64:    124: 48 83 c4 10 add rsp, 0x10
; x64:    128: 5d pop rbp
; x64:    129: c3 ret
; x64:  <l2>:
; x64:    136: b8 01 00 00 00 mov eax, 0x1
; x64:    13b: 48 83 c4 10 add rsp, 0x10
; x64:    13f: 5d pop rbp
; x64:    140: c3 ret
; x64:  <l3>:
; x64:    14d: b8 02 00 00 00 mov eax, 0x2
; x64:    152: 48 83 c4 10 add rsp, 0x10
; x64:    156: 5d pop rbp
; x64:    157: c3 ret
; x64:  <l4>:
; x64:    164: b8 04 00 00 00 mov eax, 0x4
; x64:    169: 48 83 c4 10 add rsp, 0x10
; x64:    16d: 5d pop rbp
; x64:    16e: c3 ret
; x64:  <l5>:
; x64:    17b: b8 05 00 00 00 mov eax, 0x5
; x64:    180: 48 83 c4 10 add rsp, 0x10
; x64:    184: 5d pop rbp
; x64:    185: c3 ret
; x64:  <l6>:
; x64:    192: b8 06 00 00 00 mov eax, 0x6
; x64:    197: 48 83 c4 10 add rsp, 0x10
; x64:    19b: 5d pop rbp
; x64:    19c: c3 ret
; x64:    1a9: b8 ff ff ff ff mov eax, 0xffffffff
; x64:    1ae: 48 83 c4 10 add rsp, 0x10
; x64:    1b2: 5d pop rbp
; x64:    1b3: c3 ret
; x64:     ...
; X64-LABEL: <switch_table>:
; X64:         a0: 55 push rbp
; X64-NEXT:    a1: 48 89 e5 mov rbp, rsp
; X64-NEXT:    a4: 83 ff 06 cmp edi, 0x6
; X64-NEXT:    a7: 0f 87 2f 00 00 00 ja <L0>
; X64-NEXT:    ad: 89 ff mov edi, edi
; X64-NEXT:    af: 48 8d 05 0a 00 00 00 lea rax, <switch_table+0x20>
; X64-NEXT:    b6: 48 63 3c b8 movsxd rdi, dword ptr [rax + 4*rdi]
; X64-NEXT:    ba: 48 01 f8 add rax, rdi
; X64-NEXT:    bd: ff e0 jmp rax
; X64-NEXT:    bf: 90 nop
; X64-NEXT:    c0: 21 00 and dword ptr [rax], eax
; X64-NEXT:    c2: 00 00 add byte ptr [rax], al
; X64-NEXT:    c4: 35 00 00 00 4c xor eax, 0x4c000000
; X64-NEXT:    c9: 00 00 add byte ptr [rax], al
; X64-NEXT:    cb: 00 1c 00 add byte ptr [rax + rax], bl
; X64-NEXT:    ce: 00 00 add byte ptr [rax], al
; X64-NEXT:    d0: 63 00 movsxd eax, dword ptr [rax]
; X64-NEXT:    d2: 00 00 add byte ptr [rax], al
; X64-NEXT:    d4: 7a 00 jp <L1>
; X64-NEXT:  <L1>:
; X64-NEXT:    d6: 00 00 add byte ptr [rax], al
; X64-NEXT:    d8: 91 xchg eax, ecx
; X64-NEXT:    d9: 00 00 add byte ptr [rax], al
; X64-NEXT:    db: 00 e9 add cl, ch
; X64-NEXT:    dd: 87 00 xchg dword ptr [rax], eax
; X64-NEXT:    df: 00 00 add byte ptr [rax], al
; X64-NEXT:    e1: 31 c0 xor eax, eax
; X64-NEXT:    e3: 5d pop rbp
; X64-NEXT:    e4: c3 ret
; X64-NEXT:    e5: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    ee: 0f 1f 80 00 00 00 00 nop dword ptr [rax]
; X64-NEXT:    f5: b8 01 00 00 00 mov eax, 0x1
; X64-NEXT:    fa: 5d pop rbp
; X64-NEXT:    fb: c3 ret
; X64-NEXT:    fc: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    105: 0f 1f 80 00 00 00 00 nop dword ptr [rax]
; X64-NEXT:    10c: b8 02 00 00 00 mov eax, 0x2
; X64-NEXT:    111: 5d pop rbp
; X64-NEXT:    112: c3 ret
; X64-NEXT:    113: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    11c: 0f 1f 80 00 00 00 00 nop dword ptr [rax]
; X64-NEXT:    123: b8 04 00 00 00 mov eax, 0x4
; X64-NEXT:    128: 5d pop rbp
; X64-NEXT:    129: c3 ret
; X64-NEXT:    12a: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    133: 0f 1f 80 00 00 00 00 nop dword ptr [rax]
; X64-NEXT:    13a: b8 05 00 00 00 mov eax, 0x5
; X64-NEXT:    13f: 5d pop rbp
; X64-NEXT:    140: c3 ret
; X64-NEXT:    141: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    14a: 0f 1f 80 00 00 00 00 nop dword ptr [rax]
; X64-NEXT:    151: b8 06 00 00 00 mov eax, 0x6
; X64-NEXT:    156: 5d pop rbp
; X64-NEXT:    157: c3 ret
; X64-NEXT:    158: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    161: 0f 1f 80 00 00 00 00 nop dword ptr [rax]
; X64-NEXT:    168: b8 ff ff ff ff mov eax, 0xffffffff
; X64-NEXT:    16d: 5d pop rbp
; X64-NEXT:    16e: c3 ret
; X64-NEXT:    16f: 90 nop
;
; ARM64-LABEL: <switch_table>:
; ARM64:         stp x29, x30, [sp, #-0xa0]!
; ARM64-NEXT:    mov x29, sp
; ARM64-NEXT:    cmp w0, #0x6
; ARM64-NEXT:    b.hi 0x12c <switch_table+0x3c>
; ARM64-NEXT:    adr x1, 0x110 <switch_table+0x20>
; ARM64-NEXT:    ldrsw x0, [x1, w0, uxtw #2]
; ARM64-NEXT:    add x1, x1, x0
; ARM64-NEXT:    br x1
; ARM64-NEXT:    udf #0x20
; ARM64-NEXT:    udf #0x54
; ARM64-NEXT:    udf #0x88
; ARM64-NEXT:    udf #0x1c
; ARM64-NEXT:    udf #0xbc
; ARM64-NEXT:    udf #0xf0
; ARM64-NEXT:    udf #0x124
; ARM64-NEXT:    b 0x268 <switch_table+0x178>
; ARM64-NEXT:    mov w0, #0x0 // =0
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov x0, #0x1 // =1
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov x0, #0x2 // =2
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov x0, #0x4 // =4
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov x0, #0x5 // =5
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov x0, #0x6 // =6
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov x0, #0xffffffff // =4294967295
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
entry:
  switch i32 %0, label %default [
    i32 0, label %eq0
    i32 1, label %eq1
    i32 2, label %eq2
    i32 4, label %eq4
    i32 5, label %eq5
    i32 6, label %eq6]
eq0:
  ret i32 0
eq1:
  ret i32 1
eq2:
  ret i32 2
eq4:
  ret i32 4
eq5:
  ret i32 5
eq6:
  ret i32 6
default:
  ret i32 -1
}

define i32 @switch_table2(i32 %0) {
; X64-LABEL: <switch_table2>:
; X64:         170: 55 push rbp
; X64-NEXT:    171: 48 89 e5 mov rbp, rsp
; X64-NEXT:    174: 83 ff 03 cmp edi, 0x3
; X64-NEXT:    177: 0f 82 3b 00 00 00 jb <L0>
; X64-NEXT:    17d: 83 ff 09 cmp edi, 0x9
; X64-NEXT:    180: 0f 87 32 00 00 00 ja <L0>
; X64-NEXT:    186: 89 ff mov edi, edi
; X64-NEXT:    188: 48 83 ef 03 sub rdi, 0x3
; X64-NEXT:    18c: 48 8d 05 09 00 00 00 lea rax, <switch_table2+0x2c>
; X64-NEXT:    193: 48 63 3c b8 movsxd rdi, dword ptr [rax + 4*rdi]
; X64-NEXT:    197: 48 01 f8 add rax, rdi
; X64-NEXT:    19a: ff e0 jmp rax
; X64-NEXT:    19c: 21 00 and dword ptr [rax], eax
; X64-NEXT:    19e: 00 00 add byte ptr [rax], al
; X64-NEXT:    1a0: 38 00 cmp byte ptr [rax], al
; X64-NEXT:    1a2: 00 00 add byte ptr [rax], al
; X64-NEXT:    1a4: 4f 00 00 add byte ptr [r8], r8b
; X64-NEXT:    1a7: 00 1c 00 add byte ptr [rax + rax], bl
; X64-NEXT:    1aa: 00 00 add byte ptr [rax], al
; X64-NEXT:    1ac: 66 00 00 add byte ptr [rax], al
; X64-NEXT:    1af: 00 7d 00 add byte ptr [rbp], bh
; X64-NEXT:    1b2: 00 00 add byte ptr [rax], al
; X64-NEXT:    1b4: 94 xchg eax, esp
; X64-NEXT:    1b5: 00 00 add byte ptr [rax], al
; X64-NEXT:    1b7: 00 e9 add cl, ch
; X64-NEXT:    1b9: 8a 00 mov al, byte ptr [rax]
; X64-NEXT:    1bb: 00 00 add byte ptr [rax], al
; X64-NEXT:    1bd: b8 03 00 00 00 mov eax, 0x3
; X64-NEXT:    1c2: 5d pop rbp
; X64-NEXT:    1c3: c3 ret
; X64-NEXT:    1c4: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    1cd: 0f 1f 80 00 00 00 00 nop dword ptr [rax]
; X64-NEXT:    1d4: b8 04 00 00 00 mov eax, 0x4
; X64-NEXT:    1d9: 5d pop rbp
; X64-NEXT:    1da: c3 ret
; X64-NEXT:    1db: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    1e4: 0f 1f 80 00 00 00 00 nop dword ptr [rax]
; X64-NEXT:    1eb: b8 05 00 00 00 mov eax, 0x5
; X64-NEXT:    1f0: 5d pop rbp
; X64-NEXT:    1f1: c3 ret
; X64-NEXT:    1f2: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    1fb: 0f 1f 80 00 00 00 00 nop dword ptr [rax]
; X64-NEXT:    202: b8 07 00 00 00 mov eax, 0x7
; X64-NEXT:    207: 5d pop rbp
; X64-NEXT:    208: c3 ret
; X64-NEXT:    209: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    212: 0f 1f 80 00 00 00 00 nop dword ptr [rax]
; X64-NEXT:    219: b8 08 00 00 00 mov eax, 0x8
; X64-NEXT:    21e: 5d pop rbp
; X64-NEXT:    21f: c3 ret
; X64-NEXT:    220: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    229: 0f 1f 80 00 00 00 00 nop dword ptr [rax]
; X64-NEXT:    230: b8 09 00 00 00 mov eax, 0x9
; X64-NEXT:    235: 5d pop rbp
; X64-NEXT:    236: c3 ret
; X64-NEXT:    237: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    240: 0f 1f 80 00 00 00 00 nop dword ptr [rax]
; X64-NEXT:    247: b8 ff ff ff ff mov eax, 0xffffffff
; X64-NEXT:    24c: 5d pop rbp
; X64-NEXT:    24d: c3 ret
; X64-NEXT:    24e: 66 90 nop
;
; ARM64-LABEL: <switch_table2>:
; ARM64:         stp x29, x30, [sp, #-0xa0]!
; ARM64-NEXT:    mov x29, sp
; ARM64-NEXT:    cmp w0, #0x3
; ARM64-NEXT:    b.lo 0x2c8 <switch_table2+0x48>
; ARM64-NEXT:    cmp w0, #0x9
; ARM64-NEXT:    b.hi 0x2c8 <switch_table2+0x48>
; ARM64-NEXT:    sub x0, x0, #0x3
; ARM64-NEXT:    adr x1, 0x2ac <switch_table2+0x2c>
; ARM64-NEXT:    ldrsw x0, [x1, w0, uxtw #2]
; ARM64-NEXT:    add x1, x1, x0
; ARM64-NEXT:    br x1
; ARM64-NEXT:    udf #0x20
; ARM64-NEXT:    udf #0x54
; ARM64-NEXT:    udf #0x88
; ARM64-NEXT:    udf #0x1c
; ARM64-NEXT:    udf #0xbc
; ARM64-NEXT:    udf #0xf0
; ARM64-NEXT:    udf #0x124
; ARM64-NEXT:    b 0x404 <switch_table2+0x184>
; ARM64-NEXT:    mov x0, #0x3 // =3
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov x0, #0x4 // =4
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov x0, #0x5 // =5
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov x0, #0x7 // =7
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov x0, #0x8 // =8
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov x0, #0x9 // =9
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov x0, #0xffffffff // =4294967295
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
entry:
  switch i32 %0, label %default [
    i32 3, label %eq3
    i32 4, label %eq4
    i32 5, label %eq5
    i32 7, label %eq7
    i32 8, label %eq8
    i32 9, label %eq9]
eq3:
  ret i32 3
eq4:
  ret i32 4
eq5:
  ret i32 5
eq7:
  ret i32 7
eq8:
  ret i32 8
eq9:
  ret i32 9
default:
  ret i32 -1
}


define i32 @switch_binsearch(i32 %0) {
; X64-LABEL: <switch_binsearch>:
; X64:         250: 55 push rbp
; X64-NEXT:    251: 48 89 e5 mov rbp, rsp
; X64-NEXT:    254: 83 ff 03 cmp edi, 0x3
; X64-NEXT:    257: 0f 84 67 00 00 00 je <L0>
; X64-NEXT:    25d: 0f 87 17 00 00 00 ja <L1>
; X64-NEXT:    263: 83 ff 01 cmp edi, 0x1
; X64-NEXT:    266: 0f 84 2a 00 00 00 je <L2>
; X64-NEXT:    26c: 83 ff 02 cmp edi, 0x2
; X64-NEXT:    26f: 0f 84 38 00 00 00 je <L3>
; X64-NEXT:    275: e9 17 00 00 00 jmp <L4>
; X64-NEXT:  <L1>:
; X64-NEXT:    27a: 83 ff 64 cmp edi, 0x64
; X64-NEXT:    27d: 0f 84 58 00 00 00 je <L5>
; X64-NEXT:    283: 83 ff 65 cmp edi, 0x65
; X64-NEXT:    286: 0f 84 66 00 00 00 je <L6>
; X64-NEXT:    28c: e9 00 00 00 00 jmp <L4>
; X64-NEXT:  <L4>:
; X64-NEXT:    291: e9 73 00 00 00 jmp <L7>
; X64-NEXT:  <L2>:
; X64-NEXT:    296: b8 01 00 00 00 mov eax, 0x1
; X64-NEXT:    29b: 5d pop rbp
; X64-NEXT:    29c: c3 ret
; X64-NEXT:    29d: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    2a6: 0f 1f 80 00 00 00 00 nop dword ptr [rax]
; X64-NEXT:  <L3>:
; X64-NEXT:    2ad: b8 02 00 00 00 mov eax, 0x2
; X64-NEXT:    2b2: 5d pop rbp
; X64-NEXT:    2b3: c3 ret
; X64-NEXT:    2b4: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    2bd: 0f 1f 80 00 00 00 00 nop dword ptr [rax]
; X64-NEXT:  <L0>:
; X64-NEXT:    2c4: b8 03 00 00 00 mov eax, 0x3
; X64-NEXT:    2c9: 5d pop rbp
; X64-NEXT:    2ca: c3 ret
; X64-NEXT:    2cb: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    2d4: 0f 1f 80 00 00 00 00 nop dword ptr [rax]
; X64-NEXT:  <L5>:
; X64-NEXT:    2db: b8 64 00 00 00 mov eax, 0x64
; X64-NEXT:    2e0: 5d pop rbp
; X64-NEXT:    2e1: c3 ret
; X64-NEXT:    2e2: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    2eb: 0f 1f 80 00 00 00 00 nop dword ptr [rax]
; X64-NEXT:  <L6>:
; X64-NEXT:    2f2: b8 65 00 00 00 mov eax, 0x65
; X64-NEXT:    2f7: 5d pop rbp
; X64-NEXT:    2f8: c3 ret
; X64-NEXT:    2f9: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    302: 0f 1f 80 00 00 00 00 nop dword ptr [rax]
; X64-NEXT:  <L7>:
; X64-NEXT:    309: b8 ff ff ff ff mov eax, 0xffffffff
; X64-NEXT:    30e: 5d pop rbp
; X64-NEXT:    30f: c3 ret
;
; ARM64-LABEL: <switch_binsearch>:
; ARM64:         stp x29, x30, [sp, #-0xa0]!
; ARM64-NEXT:    mov x29, sp
; ARM64-NEXT:    cmp w0, #0x3
; ARM64-NEXT:    b.eq 0x4b8 <switch_binsearch+0xa8>
; ARM64-NEXT:    b.hi 0x438 <switch_binsearch+0x28>
; ARM64-NEXT:    cmp w0, #0x1
; ARM64-NEXT:    b.eq 0x450 <switch_binsearch+0x40>
; ARM64-NEXT:    cmp w0, #0x2
; ARM64-NEXT:    b.eq 0x484 <switch_binsearch+0x74>
; ARM64-NEXT:    b 0x44c <switch_binsearch+0x3c>
; ARM64-NEXT:    cmp w0, #0x64
; ARM64-NEXT:    b.eq 0x4ec <switch_binsearch+0xdc>
; ARM64-NEXT:    cmp w0, #0x65
; ARM64-NEXT:    b.eq 0x520 <switch_binsearch+0x110>
; ARM64-NEXT:    b 0x44c <switch_binsearch+0x3c>
; ARM64-NEXT:    b 0x554 <switch_binsearch+0x144>
; ARM64-NEXT:    mov x0, #0x1 // =1
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov x0, #0x2 // =2
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov x0, #0x3 // =3
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov x0, #0x64 // =100
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov x0, #0x65 // =101
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov x0, #0xffffffff // =4294967295
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
entry:
  switch i32 %0, label %default [
    i32 1, label %eq1
    i32 2, label %eq2
    i32 3, label %eq3
    i32 100, label %eq100
    i32 101, label %eq101
  ]
eq1:
  ret i32 1
eq2:
  ret i32 2
eq3:
  ret i32 3
eq100:
  ret i32 100
eq101:
  ret i32 101
default:
  ret i32 -1
}

define i32 @switch_i32_noreuse(i32 %p) {
; X64-LABEL: <switch_i32_noreuse>:
; X64:         310: 55 push rbp
; X64-NEXT:    311: 48 89 e5 mov rbp, rsp
; X64-NEXT:    314: 53 push rbx
; X64-NEXT:    315: 89 fb mov ebx, edi
; X64-NEXT:    317: 89 d8 mov eax, ebx
; X64-NEXT:    319: 83 f8 01 cmp eax, 0x1
; X64-NEXT:    31c: 0f 84 13 00 00 00 je <L0>
; X64-NEXT:    322: 83 f8 02 cmp eax, 0x2
; X64-NEXT:    325: 0f 84 21 00 00 00 je <L1>
; X64-NEXT:    32b: e9 00 00 00 00 jmp <L2>
; X64-NEXT:  <L2>:
; X64-NEXT:    330: e9 2e 00 00 00 jmp <L3>
; X64-NEXT:  <L0>:
; X64-NEXT:    335: b8 01 00 00 00 mov eax, 0x1
; X64-NEXT:    33a: 5b pop rbx
; X64-NEXT:    33b: 5d pop rbp
; X64-NEXT:    33c: c3 ret
; X64-NEXT:    33d: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    346: 66 0f 1f 44 00 00 nop word ptr [rax + rax]
; X64-NEXT:  <L1>:
; X64-NEXT:    34c: b8 02 00 00 00 mov eax, 0x2
; X64-NEXT:    351: 5b pop rbx
; X64-NEXT:    352: 5d pop rbp
; X64-NEXT:    353: c3 ret
; X64-NEXT:    354: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    35d: 66 0f 1f 44 00 00 nop word ptr [rax + rax]
; X64-NEXT:  <L3>:
; X64-NEXT:    363: 89 d8 mov eax, ebx
; X64-NEXT:    365: 5b pop rbx
; X64-NEXT:    366: 5d pop rbp
; X64-NEXT:    367: c3 ret
; X64-NEXT:    368: 0f 1f 84 00 00 00 00 00 nop dword ptr [rax + rax]
;
; ARM64-LABEL: <switch_i32_noreuse>:
; ARM64:         stp x29, x30, [sp, #-0xa0]!
; ARM64-NEXT:    mov x29, sp
; ARM64-NEXT:    str x19, [sp, #0x10]
; ARM64-NEXT:    mov w19, w0
; ARM64-NEXT:    mov w0, w19
; ARM64-NEXT:    cmp w0, #0x1
; ARM64-NEXT:    b.eq 0x58c <switch_i32_noreuse+0x2c>
; ARM64-NEXT:    cmp w0, #0x2
; ARM64-NEXT:    b.eq 0x5c0 <switch_i32_noreuse+0x60>
; ARM64-NEXT:    b 0x588 <switch_i32_noreuse+0x28>
; ARM64-NEXT:    b 0x5f4 <switch_i32_noreuse+0x94>
; ARM64-NEXT:    mov x0, #0x1 // =1
; ARM64-NEXT:    ldr x19, [sp, #0x10]
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov x0, #0x2 // =2
; ARM64-NEXT:    ldr x19, [sp, #0x10]
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov w0, w19
; ARM64-NEXT:    ldr x19, [sp, #0x10]
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
  switch i32 %p, label %default [
    i32 1, label %l1
    i32 2, label %l2
  ]
l1:
  ret i32 1
l2:
  ret i32 2
default:
  ret i32 %p
}

define i64 @switch_i64_noreuse(i64 %p) {
; X64-LABEL: <switch_i64_noreuse>:
; X64:         370: 55 push rbp
; X64-NEXT:    371: 48 89 e5 mov rbp, rsp
; X64-NEXT:    374: 53 push rbx
; X64-NEXT:    375: 48 89 fb mov rbx, rdi
; X64-NEXT:    378: 48 89 d8 mov rax, rbx
; X64-NEXT:    37b: 48 83 f8 01 cmp rax, 0x1
; X64-NEXT:    37f: 0f 84 14 00 00 00 je <L0>
; X64-NEXT:    385: 48 83 f8 02 cmp rax, 0x2
; X64-NEXT:    389: 0f 84 21 00 00 00 je <L1>
; X64-NEXT:    38f: e9 00 00 00 00 jmp <L2>
; X64-NEXT:  <L2>:
; X64-NEXT:    394: e9 2e 00 00 00 jmp <L3>
; X64-NEXT:  <L0>:
; X64-NEXT:    399: b8 01 00 00 00 mov eax, 0x1
; X64-NEXT:    39e: 5b pop rbx
; X64-NEXT:    39f: 5d pop rbp
; X64-NEXT:    3a0: c3 ret
; X64-NEXT:    3a1: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    3aa: 66 0f 1f 44 00 00 nop word ptr [rax + rax]
; X64-NEXT:  <L1>:
; X64-NEXT:    3b0: b8 02 00 00 00 mov eax, 0x2
; X64-NEXT:    3b5: 5b pop rbx
; X64-NEXT:    3b6: 5d pop rbp
; X64-NEXT:    3b7: c3 ret
; X64-NEXT:    3b8: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    3c1: 66 0f 1f 44 00 00 nop word ptr [rax + rax]
; X64-NEXT:  <L3>:
; X64-NEXT:    3c7: 48 89 d8 mov rax, rbx
; X64-NEXT:    3ca: 5b pop rbx
; X64-NEXT:    3cb: 5d pop rbp
; X64-NEXT:    3cc: c3 ret
; X64-NEXT:    3cd: 0f 1f 00 nop dword ptr [rax]
;
; ARM64-LABEL: <switch_i64_noreuse>:
; ARM64:         stp x29, x30, [sp, #-0xa0]!
; ARM64-NEXT:    mov x29, sp
; ARM64-NEXT:    str x19, [sp, #0x10]
; ARM64-NEXT:    mov x19, x0
; ARM64-NEXT:    mov x0, x19
; ARM64-NEXT:    cmp x0, #0x1
; ARM64-NEXT:    b.eq 0x63c <switch_i64_noreuse+0x2c>
; ARM64-NEXT:    cmp x0, #0x2
; ARM64-NEXT:    b.eq 0x670 <switch_i64_noreuse+0x60>
; ARM64-NEXT:    b 0x638 <switch_i64_noreuse+0x28>
; ARM64-NEXT:    b 0x6a4 <switch_i64_noreuse+0x94>
; ARM64-NEXT:    mov x0, #0x1 // =1
; ARM64-NEXT:    ldr x19, [sp, #0x10]
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov x0, #0x2 // =2
; ARM64-NEXT:    ldr x19, [sp, #0x10]
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov x0, x19
; ARM64-NEXT:    ldr x19, [sp, #0x10]
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
  switch i64 %p, label %default [
    i64 1, label %l1
    i64 2, label %l2
  ]
l1:
  ret i64 1
l2:
  ret i64 2
default:
  ret i64 %p
}

define i32 @switch_to_self() {
; X64-LABEL: <switch_to_self>:
; X64:         3d0: 55 push rbp
; X64-NEXT:    3d1: 48 89 e5 mov rbp, rsp
; X64-NEXT:    3d4: 31 c0 xor eax, eax
; X64-NEXT:    3d6: 83 f8 35 cmp eax, 0x35
; X64-NEXT:    3d9: 0f 84 5b 01 00 00 je <L0>
; X64-NEXT:    3df: 0f 87 d7 00 00 00 ja <L1>
; X64-NEXT:    3e5: 83 f8 0a cmp eax, 0xa
; X64-NEXT:    3e8: 0f 82 0b 01 00 00 jb <L2>
; X64-NEXT:    3ee: 83 f8 34 cmp eax, 0x34
; X64-NEXT:    3f1: 0f 87 02 01 00 00 ja <L2>
; X64-NEXT:    3f7: 89 c0 mov eax, eax
; X64-NEXT:    3f9: 48 83 e8 0a sub rax, 0xa
; X64-NEXT:    3fd: 48 8d 0d 0c 00 00 00 lea rcx, <switch_to_self+0x40>
; X64-NEXT:    404: 48 63 04 81 movsxd rax, dword ptr [rcx + 4*rax]
; X64-NEXT:    408: 48 01 c1 add rcx, rax
; X64-NEXT:    40b: ff e1 jmp rcx
; X64-NEXT:    40d: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    410: c4 ff ff <unknown>
; X64-NEXT:    413: ff e9 <unknown>
; X64-NEXT:    415: 00 00 add byte ptr [rax], al
; X64-NEXT:    417: 00 e9 add cl, ch
; X64-NEXT:    419: 00 00 add byte ptr [rax], al
; X64-NEXT:    41b: 00 e9 add cl, ch
; X64-NEXT:    41d: 00 00 add byte ptr [rax], al
; X64-NEXT:    41f: 00 e9 add cl, ch
; X64-NEXT:    421: 00 00 add byte ptr [rax], al
; X64-NEXT:    423: 00 e9 add cl, ch
; X64-NEXT:    425: 00 00 add byte ptr [rax], al
; X64-NEXT:    427: 00 e9 add cl, ch
; X64-NEXT:    429: 00 00 add byte ptr [rax], al
; X64-NEXT:    42b: 00 e9 add cl, ch
; X64-NEXT:    42d: 00 00 add byte ptr [rax], al
; X64-NEXT:    42f: 00 e9 add cl, ch
; X64-NEXT:    431: 00 00 add byte ptr [rax], al
; X64-NEXT:    433: 00 e9 add cl, ch
; X64-NEXT:    435: 00 00 add byte ptr [rax], al
; X64-NEXT:    437: 00 e9 add cl, ch
; X64-NEXT:    439: 00 00 add byte ptr [rax], al
; X64-NEXT:    43b: 00 e9 add cl, ch
; X64-NEXT:    43d: 00 00 add byte ptr [rax], al
; X64-NEXT:    43f: 00 e9 add cl, ch
; X64-NEXT:    441: 00 00 add byte ptr [rax], al
; X64-NEXT:    443: 00 e9 add cl, ch
; X64-NEXT:    445: 00 00 add byte ptr [rax], al
; X64-NEXT:    447: 00 e9 add cl, ch
; X64-NEXT:    449: 00 00 add byte ptr [rax], al
; X64-NEXT:    44b: 00 e9 add cl, ch
; X64-NEXT:    44d: 00 00 add byte ptr [rax], al
; X64-NEXT:    44f: 00 e9 add cl, ch
; X64-NEXT:    451: 00 00 add byte ptr [rax], al
; X64-NEXT:    453: 00 e9 add cl, ch
; X64-NEXT:    455: 00 00 add byte ptr [rax], al
; X64-NEXT:    457: 00 e9 add cl, ch
; X64-NEXT:    459: 00 00 add byte ptr [rax], al
; X64-NEXT:    45b: 00 e9 add cl, ch
; X64-NEXT:    45d: 00 00 add byte ptr [rax], al
; X64-NEXT:    45f: 00 e9 add cl, ch
; X64-NEXT:    461: 00 00 add byte ptr [rax], al
; X64-NEXT:    463: 00 e9 add cl, ch
; X64-NEXT:    465: 00 00 add byte ptr [rax], al
; X64-NEXT:    467: 00 e9 add cl, ch
; X64-NEXT:    469: 00 00 add byte ptr [rax], al
; X64-NEXT:    46b: 00 e9 add cl, ch
; X64-NEXT:    46d: 00 00 add byte ptr [rax], al
; X64-NEXT:    46f: 00 e9 add cl, ch
; X64-NEXT:    471: 00 00 add byte ptr [rax], al
; X64-NEXT:    473: 00 e9 add cl, ch
; X64-NEXT:    475: 00 00 add byte ptr [rax], al
; X64-NEXT:    477: 00 e9 add cl, ch
; X64-NEXT:    479: 00 00 add byte ptr [rax], al
; X64-NEXT:    47b: 00 e9 add cl, ch
; X64-NEXT:    47d: 00 00 add byte ptr [rax], al
; X64-NEXT:    47f: 00 e9 add cl, ch
; X64-NEXT:    481: 00 00 add byte ptr [rax], al
; X64-NEXT:    483: 00 e9 add cl, ch
; X64-NEXT:    485: 00 00 add byte ptr [rax], al
; X64-NEXT:    487: 00 e9 add cl, ch
; X64-NEXT:    489: 00 00 add byte ptr [rax], al
; X64-NEXT:    48b: 00 e9 add cl, ch
; X64-NEXT:    48d: 00 00 add byte ptr [rax], al
; X64-NEXT:    48f: 00 e9 add cl, ch
; X64-NEXT:    491: 00 00 add byte ptr [rax], al
; X64-NEXT:    493: 00 e9 add cl, ch
; X64-NEXT:    495: 00 00 add byte ptr [rax], al
; X64-NEXT:    497: 00 e9 add cl, ch
; X64-NEXT:    499: 00 00 add byte ptr [rax], al
; X64-NEXT:    49b: 00 e9 add cl, ch
; X64-NEXT:    49d: 00 00 add byte ptr [rax], al
; X64-NEXT:    49f: 00 e9 add cl, ch
; X64-NEXT:    4a1: 00 00 add byte ptr [rax], al
; X64-NEXT:    4a3: 00 e9 add cl, ch
; X64-NEXT:    4a5: 00 00 add byte ptr [rax], al
; X64-NEXT:    4a7: 00 2a add byte ptr [rdx], ch
; X64-NEXT:    4a9: 01 00 add dword ptr [rax], eax
; X64-NEXT:    4ab: 00 2a add byte ptr [rdx], ch
; X64-NEXT:    4ad: 01 00 add dword ptr [rax], eax
; X64-NEXT:    4af: 00 2a add byte ptr [rdx], ch
; X64-NEXT:    4b1: 01 00 add dword ptr [rax], eax
; X64-NEXT:    4b3: 00 2a add byte ptr [rdx], ch
; X64-NEXT:    4b5: 01 00 add dword ptr [rax], eax
; X64-NEXT:    4b7: 00 2a add byte ptr [rdx], ch
; X64-NEXT:    4b9: 01 00 add dword ptr [rax], eax
; X64-NEXT:    4bb: 00 83 f8 62 0f 84 add byte ptr [rbx - 0x7bf09d08], al
; X64-NEXT:    4c1: 4d 00 00 add byte ptr [r8], r8b
; X64-NEXT:    4c4: 00 0f add byte ptr [rdi], cl
; X64-NEXT:    4c6: 87 17 xchg dword ptr [rdi], edx
; X64-NEXT:    4c8: 00 00 add byte ptr [rax], al
; X64-NEXT:    4ca: 00 83 f8 36 0f 84 add byte ptr [rbx - 0x7bf0c908], al
; X64-NEXT:    4d0: 66 00 00 add byte ptr [rax], al
; X64-NEXT:    4d3: 00 83 f8 37 0f 84 add byte ptr [rbx - 0x7bf0c808], al
; X64-NEXT:    4d9: 5d pop rbp
; X64-NEXT:    4da: 00 00 add byte ptr [rax], al
; X64-NEXT:    4dc: 00 e9 add cl, ch
; X64-NEXT:    4de: 17 <unknown>
; X64-NEXT:    4df: 00 00 add byte ptr [rax], al
; X64-NEXT:    4e1: 00 83 f8 66 0f 84 add byte ptr [rbx - 0x7bf09908], al
; X64-NEXT:    4e7: 3b 00 cmp eax, dword ptr [rax]
; X64-NEXT:    4e9: 00 00 add byte ptr [rax], al
; X64-NEXT:    4eb: 83 f8 72 cmp eax, 0x72
; X64-NEXT:    4ee: 0f 84 0a 00 00 00 je <L3>
; X64-NEXT:    4f4: e9 00 00 00 00 jmp <L2>
; X64-NEXT:  <L2>:
; X64-NEXT:    4f9: e9 3c 00 00 00 jmp <L0>
; X64-NEXT:  <L3>:
; X64-NEXT:    4fe: 31 c0 xor eax, eax
; X64-NEXT:    500: 5d pop rbp
; X64-NEXT:    501: c3 ret
; X64-NEXT:    502: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    50b: 0f 1f 80 00 00 00 00 nop dword ptr [rax]
; X64-NEXT:    512: 31 c0 xor eax, eax
; X64-NEXT:    514: 5d pop rbp
; X64-NEXT:    515: c3 ret
; X64-NEXT:    516: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    51f: 0f 1f 80 00 00 00 00 nop dword ptr [rax]
; X64-NEXT:    526: 31 c0 xor eax, eax
; X64-NEXT:    528: 5d pop rbp
; X64-NEXT:    529: c3 ret
; X64-NEXT:    52a: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    533: 0f 1f 80 00 00 00 00 nop dword ptr [rax]
; X64-NEXT:  <L0>:
; X64-NEXT:    53a: 31 c0 xor eax, eax
; X64-NEXT:    53c: 5d pop rbp
; X64-NEXT:    53d: c3 ret
;
; ARM64-LABEL: <switch_to_self>:
; ARM64:         stp x29, x30, [sp, #-0xa0]!
; ARM64-NEXT:    mov x29, sp
; ARM64-NEXT:    mov w0, #0x0 // =0
; ARM64-NEXT:    cmp w0, #0x35
; ARM64-NEXT:    b.eq 0x87c <switch_to_self+0x1bc>
; ARM64-NEXT:    b.hi 0x7a8 <switch_to_self+0xe8>
; ARM64-NEXT:    cmp w0, #0xa
; ARM64-NEXT:    b.lo 0x7dc <switch_to_self+0x11c>
; ARM64-NEXT:    cmp w0, #0x34
; ARM64-NEXT:    b.hi 0x7dc <switch_to_self+0x11c>
; ARM64-NEXT:    sub x0, x0, #0xa
; ARM64-NEXT:    adr x1, 0x6fc <switch_to_self+0x3c>
; ARM64-NEXT:    ldrsw x0, [x1, w0, uxtw #2]
; ARM64-NEXT:    add x1, x1, x0
; ARM64-NEXT:    br x1
; ARM64-NEXT:    <unknown>
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0x180
; ARM64-NEXT:    udf #0x180
; ARM64-NEXT:    udf #0x180
; ARM64-NEXT:    udf #0x180
; ARM64-NEXT:    udf #0x180
; ARM64-NEXT:    cmp w0, #0x62
; ARM64-NEXT:    b.eq 0x814 <switch_to_self+0x154>
; ARM64-NEXT:    b.hi 0x7c8 <switch_to_self+0x108>
; ARM64-NEXT:    cmp w0, #0x36
; ARM64-NEXT:    b.eq 0x87c <switch_to_self+0x1bc>
; ARM64-NEXT:    cmp w0, #0x37
; ARM64-NEXT:    b.eq 0x87c <switch_to_self+0x1bc>
; ARM64-NEXT:    b 0x7dc <switch_to_self+0x11c>
; ARM64-NEXT:    cmp w0, #0x66
; ARM64-NEXT:    b.eq 0x848 <switch_to_self+0x188>
; ARM64-NEXT:    cmp w0, #0x72
; ARM64-NEXT:    b.eq 0x7e0 <switch_to_self+0x120>
; ARM64-NEXT:    b 0x7dc <switch_to_self+0x11c>
; ARM64-NEXT:    b 0x87c <switch_to_self+0x1bc>
; ARM64-NEXT:    mov w0, #0x0 // =0
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov w0, #0x0 // =0
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov w0, #0x0 // =0
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
; ARM64-NEXT:     ...
; ARM64-NEXT:    mov w0, #0x0 // =0
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
  br label %1

1:
  switch i32 0, label %5 [
    i32 55, label %5
    i32 114, label %2
    i32 54, label %5
    i32 98, label %3
    i32 102, label %4
    i32 10, label %1
    i32 48, label %5
    i32 49, label %5
    i32 50, label %5
    i32 51, label %5
    i32 52, label %5
    i32 53, label %5
  ]

2:
  ret i32 0

3:
  ret i32 0

4:
  ret i32 0

5:
  ret i32 0
}
