; NOTE: Assertions have been autogenerated by test/update_tpde_llc_test_checks.py UTC_ARGS: --version 5
; SPDX-FileCopyrightText: 2025 Contributors to TPDE <https://tpde.org>
;
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

; RUN: tpde-llc --target=x86_64 %s | llvm-objdump -d -r --symbolize-operands --x86-asm-syntax=intel - | FileCheck %s -check-prefixes=X64
; RUN: tpde-llc --target=aarch64 %s | %objdump | FileCheck %s -check-prefixes=ARM64

define i32 @empty_switch(i32 %0) {
; X64-LABEL: <empty_switch>:
; X64:         0: e9 00 00 00 00 jmp <L0>
; X64-NEXT:  <L0>:
; X64-NEXT:    5: e9 00 00 00 00 jmp <L1>
; X64-NEXT:  <L1>:
; X64-NEXT:    a: b8 ff ff ff ff mov eax, 0xffffffff
; X64-NEXT:    f: c3 ret
;
; ARM64-LABEL: <empty_switch>:
; ARM64:         b 0x4 <empty_switch+0x4>
; ARM64-NEXT:    b 0x8 <empty_switch+0x8>
; ARM64-NEXT:    mov x0, #0xffffffff // =4294967295
; ARM64-NEXT:    ret
entry:
  switch i32 %0, label %default []
default:
  ret i32 -1
}

define i32 @basic_switch(i32 %0) {
; X64-LABEL: <basic_switch>:
; X64:         10: 83 ff 00 cmp edi, 0x0
; X64-NEXT:    13: 0f 84 1c 00 00 00 je <L0>
; X64-NEXT:    19: 83 ff 01 cmp edi, 0x1
; X64-NEXT:    1c: 0f 84 1a 00 00 00 je <L1>
; X64-NEXT:    22: 83 ff 02 cmp edi, 0x2
; X64-NEXT:    25: 0f 84 1b 00 00 00 je <L2>
; X64-NEXT:    2b: e9 00 00 00 00 jmp <L3>
; X64-NEXT:  <L3>:
; X64-NEXT:    30: e9 1b 00 00 00 jmp <L4>
; X64-NEXT:  <L0>:
; X64-NEXT:    35: 31 c0 xor eax, eax
; X64-NEXT:    37: e9 19 00 00 00 jmp <L5>
; X64-NEXT:  <L1>:
; X64-NEXT:    3c: b8 01 00 00 00 mov eax, 0x1
; X64-NEXT:    41: e9 0f 00 00 00 jmp <L5>
; X64-NEXT:  <L2>:
; X64-NEXT:    46: b8 02 00 00 00 mov eax, 0x2
; X64-NEXT:    4b: e9 05 00 00 00 jmp <L5>
; X64-NEXT:  <L4>:
; X64-NEXT:    50: b8 ff ff ff ff mov eax, 0xffffffff
; X64-NEXT:  <L5>:
; X64-NEXT:    55: c3 ret
; X64-NEXT:    56: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    5f: 90 nop
;
; ARM64-LABEL: <basic_switch>:
; ARM64:         cmp w0, #0x0
; ARM64-NEXT:    b.eq 0x30 <basic_switch+0x20>
; ARM64-NEXT:    cmp w0, #0x1
; ARM64-NEXT:    b.eq 0x38 <basic_switch+0x28>
; ARM64-NEXT:    cmp w0, #0x2
; ARM64-NEXT:    b.eq 0x40 <basic_switch+0x30>
; ARM64-NEXT:    b 0x2c <basic_switch+0x1c>
; ARM64-NEXT:    b 0x48 <basic_switch+0x38>
; ARM64-NEXT:    mov w0, #0x0 // =0
; ARM64-NEXT:    b 0x4c <basic_switch+0x3c>
; ARM64-NEXT:    mov x0, #0x1 // =1
; ARM64-NEXT:    b 0x4c <basic_switch+0x3c>
; ARM64-NEXT:    mov x0, #0x2 // =2
; ARM64-NEXT:    b 0x4c <basic_switch+0x3c>
; ARM64-NEXT:    mov x0, #0xffffffff // =4294967295
; ARM64-NEXT:    ret
entry:
  switch i32 %0, label %default [ i32 0, label %eq0
                                  i32 1, label %eq1
                                  i32 2, label %eq2]
eq0:
  ret i32 0
eq1:
  ret i32 1
eq2:
  ret i32 2
default:
  ret i32 -1
}

define i32 @switch_table(i32 %0) {
; x64-label: switch_table>:
; x64:    b0: 55 push rbp
; x64:    b1: 48 89 e5 mov rbp, rsp
; x64:    b4: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; x64:    bd: 48 81 ec 10 00 00 00 sub rsp, 0x10
; x64:    c4: 83 ff 06 cmp edi, 0x6
; x64:    c7: 0f 87 2f 00 00 00 ja <l0>
; x64:    cd: 89 ff mov edi, edi
; x64:    cf: 48 8d 05 0a 00 00 00 lea rax, <switch_table+0x30>
; x64:    d6: 48 63 3c b8 movsxd rdi, dword ptr [rax + 4*rdi]
; x64:    da: 48 01 f8 add rax, rdi
; x64:    dd: ff e0 jmp rax
; x64:    df: 00 21 add byte ptr [rcx], ah
; x64:    e1: 00 00 add byte ptr [rax], al
; x64:    e3: 00 26 add byte ptr [rsi], ah
; x64:    e5: 00 00 add byte ptr [rax], al
; x64:    e7: 00 2b add byte ptr [rbx], ch
; x64:    e9: 00 00 add byte ptr [rax], al
; x64:    eb: 00 1c 00 add byte ptr [rax + rax], bl
; x64:    ee: 00 00 add byte ptr [rax], al
; x64:    f0: 30 00 xor byte ptr [rax], al
; x64:    f2: 00 00 add byte ptr [rax], al
; x64:    f4: 35 00 00 00 3a xor eax, 0x3a000000
; x64:    f9: 00 00 add byte ptr [rax], al
; x64:    fb: 00 e9 add cl, ch
; x64:    fd: a8 00 test al, 0x0
; x64:    ff: 00 00 add byte ptr [rax], al
; x64:    101: e9 19 00 00 00 jmp <l1>
; x64:    106: e9 2b 00 00 00 jmp <l2>
; x64:    10b: e9 3d 00 00 00 jmp <l3>
; x64:    110: e9 4f 00 00 00 jmp <l4>
; x64:    115: e9 61 00 00 00 jmp <l5>
; x64:    11a: e9 73 00 00 00 jmp <l6>
; x64:  <l1>:
; x64:    11f: b8 00 00 00 00 mov eax, 0x0
; x64:    124: 48 83 c4 10 add rsp, 0x10
; x64:    128: 5d pop rbp
; x64:    129: c3 ret
; x64:  <l2>:
; x64:    136: b8 01 00 00 00 mov eax, 0x1
; x64:    13b: 48 83 c4 10 add rsp, 0x10
; x64:    13f: 5d pop rbp
; x64:    140: c3 ret
; x64:  <l3>:
; x64:    14d: b8 02 00 00 00 mov eax, 0x2
; x64:    152: 48 83 c4 10 add rsp, 0x10
; x64:    156: 5d pop rbp
; x64:    157: c3 ret
; x64:  <l4>:
; x64:    164: b8 04 00 00 00 mov eax, 0x4
; x64:    169: 48 83 c4 10 add rsp, 0x10
; x64:    16d: 5d pop rbp
; x64:    16e: c3 ret
; x64:  <l5>:
; x64:    17b: b8 05 00 00 00 mov eax, 0x5
; x64:    180: 48 83 c4 10 add rsp, 0x10
; x64:    184: 5d pop rbp
; x64:    185: c3 ret
; x64:  <l6>:
; x64:    192: b8 06 00 00 00 mov eax, 0x6
; x64:    197: 48 83 c4 10 add rsp, 0x10
; x64:    19b: 5d pop rbp
; x64:    19c: c3 ret
; x64:    1a9: b8 ff ff ff ff mov eax, 0xffffffff
; x64:    1ae: 48 83 c4 10 add rsp, 0x10
; x64:    1b2: 5d pop rbp
; x64:    1b3: c3 ret
; x64:     ...
; X64-LABEL: <switch_table>:
; X64:         60: 83 ff 06 cmp edi, 0x6
; X64-NEXT:    63: 0f 87 2f 00 00 00 ja <L0>
; X64-NEXT:    69: 89 ff mov edi, edi
; X64-NEXT:    6b: 48 8d 05 0a 00 00 00 lea rax, <switch_table+0x1c>
; X64-NEXT:    72: 48 63 3c b8 movsxd rdi, dword ptr [rax + 4*rdi]
; X64-NEXT:    76: 48 01 f8 add rax, rdi
; X64-NEXT:    79: ff e0 jmp rax
; X64-NEXT:    7b: 90 nop
; X64-NEXT:    7c: 21 00 and dword ptr [rax], eax
; X64-NEXT:    7e: 00 00 add byte ptr [rax], al
; X64-NEXT:    80: 28 00 sub byte ptr [rax], al
; X64-NEXT:    82: 00 00 add byte ptr [rax], al
; X64-NEXT:    84: 32 00 xor al, byte ptr [rax]
; X64-NEXT:    86: 00 00 add byte ptr [rax], al
; X64-NEXT:    88: 1c 00 sbb al, 0x0
; X64-NEXT:    8a: 00 00 add byte ptr [rax], al
; X64-NEXT:    8c: 3c 00 cmp al, 0x0
; X64-NEXT:    8e: 00 00 add byte ptr [rax], al
; X64-NEXT:    90: 46 00 00 add byte ptr [rax], r8b
; X64-NEXT:    93: 00 50 00 add byte ptr [rax], dl
; X64-NEXT:    96: 00 00 add byte ptr [rax], al
; X64-NEXT:  <L0>:
; X64-NEXT:    98: e9 39 00 00 00 jmp <L1>
; X64-NEXT:    9d: 31 c0 xor eax, eax
; X64-NEXT:    9f: e9 37 00 00 00 jmp <L2>
; X64-NEXT:    a4: b8 01 00 00 00 mov eax, 0x1
; X64-NEXT:    a9: e9 2d 00 00 00 jmp <L2>
; X64-NEXT:    ae: b8 02 00 00 00 mov eax, 0x2
; X64-NEXT:    b3: e9 23 00 00 00 jmp <L2>
; X64-NEXT:    b8: b8 04 00 00 00 mov eax, 0x4
; X64-NEXT:    bd: e9 19 00 00 00 jmp <L2>
; X64-NEXT:    c2: b8 05 00 00 00 mov eax, 0x5
; X64-NEXT:    c7: e9 0f 00 00 00 jmp <L2>
; X64-NEXT:    cc: b8 06 00 00 00 mov eax, 0x6
; X64-NEXT:    d1: e9 05 00 00 00 jmp <L2>
; X64-NEXT:  <L1>:
; X64-NEXT:    d6: b8 ff ff ff ff mov eax, 0xffffffff
; X64-NEXT:  <L2>:
; X64-NEXT:    db: c3 ret
; X64-NEXT:    dc: 0f 1f 40 00 nop dword ptr [rax]
;
; ARM64-LABEL: <switch_table>:
; ARM64:         cmp w0, #0x6
; ARM64-NEXT:    b.hi 0x84 <switch_table+0x34>
; ARM64-NEXT:    adr x1, 0x68 <switch_table+0x18>
; ARM64-NEXT:    ldrsw x0, [x1, w0, uxtw #2]
; ARM64-NEXT:    add x1, x1, x0
; ARM64-NEXT:    br x1
; ARM64-NEXT:    udf #0x20
; ARM64-NEXT:    udf #0x28
; ARM64-NEXT:    udf #0x30
; ARM64-NEXT:    udf #0x1c
; ARM64-NEXT:    udf #0x38
; ARM64-NEXT:    udf #0x40
; ARM64-NEXT:    udf #0x48
; ARM64-NEXT:    b 0xb8 <switch_table+0x68>
; ARM64-NEXT:    mov w0, #0x0 // =0
; ARM64-NEXT:    b 0xbc <switch_table+0x6c>
; ARM64-NEXT:    mov x0, #0x1 // =1
; ARM64-NEXT:    b 0xbc <switch_table+0x6c>
; ARM64-NEXT:    mov x0, #0x2 // =2
; ARM64-NEXT:    b 0xbc <switch_table+0x6c>
; ARM64-NEXT:    mov x0, #0x4 // =4
; ARM64-NEXT:    b 0xbc <switch_table+0x6c>
; ARM64-NEXT:    mov x0, #0x5 // =5
; ARM64-NEXT:    b 0xbc <switch_table+0x6c>
; ARM64-NEXT:    mov x0, #0x6 // =6
; ARM64-NEXT:    b 0xbc <switch_table+0x6c>
; ARM64-NEXT:    mov x0, #0xffffffff // =4294967295
; ARM64-NEXT:    ret
entry:
  switch i32 %0, label %default [
    i32 0, label %eq0
    i32 1, label %eq1
    i32 2, label %eq2
    i32 4, label %eq4
    i32 5, label %eq5
    i32 6, label %eq6]
eq0:
  ret i32 0
eq1:
  ret i32 1
eq2:
  ret i32 2
eq4:
  ret i32 4
eq5:
  ret i32 5
eq6:
  ret i32 6
default:
  ret i32 -1
}

define i32 @switch_table2(i32 %0) {
; X64-LABEL: <switch_table2>:
; X64:         e0: 83 ff 03 cmp edi, 0x3
; X64-NEXT:    e3: 0f 82 3b 00 00 00 jb <L0>
; X64-NEXT:    e9: 83 ff 09 cmp edi, 0x9
; X64-NEXT:    ec: 0f 87 32 00 00 00 ja <L0>
; X64-NEXT:    f2: 89 ff mov edi, edi
; X64-NEXT:    f4: 48 83 ef 03 sub rdi, 0x3
; X64-NEXT:    f8: 48 8d 05 09 00 00 00 lea rax, <switch_table2+0x28>
; X64-NEXT:    ff: 48 63 3c b8 movsxd rdi, dword ptr [rax + 4*rdi]
; X64-NEXT:    103: 48 01 f8 add rax, rdi
; X64-NEXT:    106: ff e0 jmp rax
; X64-NEXT:    108: 21 00 and dword ptr [rax], eax
; X64-NEXT:    10a: 00 00 add byte ptr [rax], al
; X64-NEXT:    10c: 2b 00 sub eax, dword ptr [rax]
; X64-NEXT:    10e: 00 00 add byte ptr [rax], al
; X64-NEXT:    110: 35 00 00 00 1c xor eax, 0x1c000000
; X64-NEXT:    115: 00 00 add byte ptr [rax], al
; X64-NEXT:    117: 00 3f add byte ptr [rdi], bh
; X64-NEXT:    119: 00 00 add byte ptr [rax], al
; X64-NEXT:    11b: 00 49 00 add byte ptr [rcx], cl
; X64-NEXT:    11e: 00 00 add byte ptr [rax], al
; X64-NEXT:    120: 53 push rbx
; X64-NEXT:    121: 00 00 add byte ptr [rax], al
; X64-NEXT:    123: 00 e9 add cl, ch
; X64-NEXT:    125: 3c 00 cmp al, 0x0
; X64-NEXT:    127: 00 00 add byte ptr [rax], al
; X64-NEXT:    129: b8 03 00 00 00 mov eax, 0x3
; X64-NEXT:    12e: e9 37 00 00 00 jmp <L1>
; X64-NEXT:    133: b8 04 00 00 00 mov eax, 0x4
; X64-NEXT:    138: e9 2d 00 00 00 jmp <L1>
; X64-NEXT:    13d: b8 05 00 00 00 mov eax, 0x5
; X64-NEXT:    142: e9 23 00 00 00 jmp <L1>
; X64-NEXT:    147: b8 07 00 00 00 mov eax, 0x7
; X64-NEXT:    14c: e9 19 00 00 00 jmp <L1>
; X64-NEXT:    151: b8 08 00 00 00 mov eax, 0x8
; X64-NEXT:    156: e9 0f 00 00 00 jmp <L1>
; X64-NEXT:    15b: b8 09 00 00 00 mov eax, 0x9
; X64-NEXT:    160: e9 05 00 00 00 jmp <L1>
; X64-NEXT:    165: b8 ff ff ff ff mov eax, 0xffffffff
; X64-NEXT:  <L1>:
; X64-NEXT:    16a: c3 ret
; X64-NEXT:    16b: 0f 1f 44 00 00 nop dword ptr [rax + rax]
;
; ARM64-LABEL: <switch_table2>:
; ARM64:         cmp w0, #0x3
; ARM64-NEXT:    b.lo 0x100 <switch_table2+0x40>
; ARM64-NEXT:    cmp w0, #0x9
; ARM64-NEXT:    b.hi 0x100 <switch_table2+0x40>
; ARM64-NEXT:    sub x0, x0, #0x3
; ARM64-NEXT:    adr x1, 0xe4 <switch_table2+0x24>
; ARM64-NEXT:    ldrsw x0, [x1, w0, uxtw #2]
; ARM64-NEXT:    add x1, x1, x0
; ARM64-NEXT:    br x1
; ARM64-NEXT:    udf #0x20
; ARM64-NEXT:    udf #0x28
; ARM64-NEXT:    udf #0x30
; ARM64-NEXT:    udf #0x1c
; ARM64-NEXT:    udf #0x38
; ARM64-NEXT:    udf #0x40
; ARM64-NEXT:    udf #0x48
; ARM64-NEXT:    b 0x134 <switch_table2+0x74>
; ARM64-NEXT:    mov x0, #0x3 // =3
; ARM64-NEXT:    b 0x138 <switch_table2+0x78>
; ARM64-NEXT:    mov x0, #0x4 // =4
; ARM64-NEXT:    b 0x138 <switch_table2+0x78>
; ARM64-NEXT:    mov x0, #0x5 // =5
; ARM64-NEXT:    b 0x138 <switch_table2+0x78>
; ARM64-NEXT:    mov x0, #0x7 // =7
; ARM64-NEXT:    b 0x138 <switch_table2+0x78>
; ARM64-NEXT:    mov x0, #0x8 // =8
; ARM64-NEXT:    b 0x138 <switch_table2+0x78>
; ARM64-NEXT:    mov x0, #0x9 // =9
; ARM64-NEXT:    b 0x138 <switch_table2+0x78>
; ARM64-NEXT:    mov x0, #0xffffffff // =4294967295
; ARM64-NEXT:    ret
entry:
  switch i32 %0, label %default [
    i32 3, label %eq3
    i32 4, label %eq4
    i32 5, label %eq5
    i32 7, label %eq7
    i32 8, label %eq8
    i32 9, label %eq9]
eq3:
  ret i32 3
eq4:
  ret i32 4
eq5:
  ret i32 5
eq7:
  ret i32 7
eq8:
  ret i32 8
eq9:
  ret i32 9
default:
  ret i32 -1
}


define i32 @switch_binsearch(i32 %0) {
; X64-LABEL: <switch_binsearch>:
; X64:         170: 83 ff 03 cmp edi, 0x3
; X64-NEXT:    173: 0f 84 4d 00 00 00 je <L0>
; X64-NEXT:    179: 0f 87 17 00 00 00 ja <L1>
; X64-NEXT:    17f: 83 ff 01 cmp edi, 0x1
; X64-NEXT:    182: 0f 84 2a 00 00 00 je <L2>
; X64-NEXT:    188: 83 ff 02 cmp edi, 0x2
; X64-NEXT:    18b: 0f 84 2b 00 00 00 je <L3>
; X64-NEXT:    191: e9 17 00 00 00 jmp <L4>
; X64-NEXT:  <L1>:
; X64-NEXT:    196: 83 ff 64 cmp edi, 0x64
; X64-NEXT:    199: 0f 84 31 00 00 00 je <L5>
; X64-NEXT:    19f: 83 ff 65 cmp edi, 0x65
; X64-NEXT:    1a2: 0f 84 32 00 00 00 je <L6>
; X64-NEXT:    1a8: e9 00 00 00 00 jmp <L4>
; X64-NEXT:  <L4>:
; X64-NEXT:    1ad: e9 32 00 00 00 jmp <L7>
; X64-NEXT:  <L2>:
; X64-NEXT:    1b2: b8 01 00 00 00 mov eax, 0x1
; X64-NEXT:    1b7: e9 2d 00 00 00 jmp <L8>
; X64-NEXT:  <L3>:
; X64-NEXT:    1bc: b8 02 00 00 00 mov eax, 0x2
; X64-NEXT:    1c1: e9 23 00 00 00 jmp <L8>
; X64-NEXT:  <L0>:
; X64-NEXT:    1c6: b8 03 00 00 00 mov eax, 0x3
; X64-NEXT:    1cb: e9 19 00 00 00 jmp <L8>
; X64-NEXT:  <L5>:
; X64-NEXT:    1d0: b8 64 00 00 00 mov eax, 0x64
; X64-NEXT:    1d5: e9 0f 00 00 00 jmp <L8>
; X64-NEXT:  <L6>:
; X64-NEXT:    1da: b8 65 00 00 00 mov eax, 0x65
; X64-NEXT:    1df: e9 05 00 00 00 jmp <L8>
; X64-NEXT:  <L7>:
; X64-NEXT:    1e4: b8 ff ff ff ff mov eax, 0xffffffff
; X64-NEXT:  <L8>:
; X64-NEXT:    1e9: c3 ret
; X64-NEXT:    1ea: 66 0f 1f 44 00 00 nop word ptr [rax + rax]
;
; ARM64-LABEL: <switch_binsearch>:
; ARM64:         cmp w0, #0x3
; ARM64-NEXT:    b.eq 0x188 <switch_binsearch+0x48>
; ARM64-NEXT:    b.hi 0x160 <switch_binsearch+0x20>
; ARM64-NEXT:    cmp w0, #0x1
; ARM64-NEXT:    b.eq 0x178 <switch_binsearch+0x38>
; ARM64-NEXT:    cmp w0, #0x2
; ARM64-NEXT:    b.eq 0x180 <switch_binsearch+0x40>
; ARM64-NEXT:    b 0x174 <switch_binsearch+0x34>
; ARM64-NEXT:    cmp w0, #0x64
; ARM64-NEXT:    b.eq 0x190 <switch_binsearch+0x50>
; ARM64-NEXT:    cmp w0, #0x65
; ARM64-NEXT:    b.eq 0x198 <switch_binsearch+0x58>
; ARM64-NEXT:    b 0x174 <switch_binsearch+0x34>
; ARM64-NEXT:    b 0x1a0 <switch_binsearch+0x60>
; ARM64-NEXT:    mov x0, #0x1 // =1
; ARM64-NEXT:    b 0x1a4 <switch_binsearch+0x64>
; ARM64-NEXT:    mov x0, #0x2 // =2
; ARM64-NEXT:    b 0x1a4 <switch_binsearch+0x64>
; ARM64-NEXT:    mov x0, #0x3 // =3
; ARM64-NEXT:    b 0x1a4 <switch_binsearch+0x64>
; ARM64-NEXT:    mov x0, #0x64 // =100
; ARM64-NEXT:    b 0x1a4 <switch_binsearch+0x64>
; ARM64-NEXT:    mov x0, #0x65 // =101
; ARM64-NEXT:    b 0x1a4 <switch_binsearch+0x64>
; ARM64-NEXT:    mov x0, #0xffffffff // =4294967295
; ARM64-NEXT:    ret
entry:
  switch i32 %0, label %default [
    i32 1, label %eq1
    i32 2, label %eq2
    i32 3, label %eq3
    i32 100, label %eq100
    i32 101, label %eq101
  ]
eq1:
  ret i32 1
eq2:
  ret i32 2
eq3:
  ret i32 3
eq100:
  ret i32 100
eq101:
  ret i32 101
default:
  ret i32 -1
}

define i32 @switch_i32_noreuse(i32 %p) {
; X64-LABEL: <switch_i32_noreuse>:
; X64:         1f0: 55 push rbp
; X64-NEXT:    1f1: 48 89 e5 mov rbp, rsp
; X64-NEXT:    1f4: 53 push rbx
; X64-NEXT:    1f5: 89 fb mov ebx, edi
; X64-NEXT:    1f7: 89 d8 mov eax, ebx
; X64-NEXT:    1f9: 83 f8 01 cmp eax, 0x1
; X64-NEXT:    1fc: 0f 84 13 00 00 00 je <L0>
; X64-NEXT:    202: 83 f8 02 cmp eax, 0x2
; X64-NEXT:    205: 0f 84 14 00 00 00 je <L1>
; X64-NEXT:    20b: e9 00 00 00 00 jmp <L2>
; X64-NEXT:  <L2>:
; X64-NEXT:    210: e9 14 00 00 00 jmp <L3>
; X64-NEXT:  <L0>:
; X64-NEXT:    215: b8 01 00 00 00 mov eax, 0x1
; X64-NEXT:    21a: e9 0c 00 00 00 jmp <L4>
; X64-NEXT:  <L1>:
; X64-NEXT:    21f: b8 02 00 00 00 mov eax, 0x2
; X64-NEXT:    224: e9 02 00 00 00 jmp <L4>
; X64-NEXT:  <L3>:
; X64-NEXT:    229: 89 d8 mov eax, ebx
; X64-NEXT:  <L4>:
; X64-NEXT:    22b: 5b pop rbx
; X64-NEXT:    22c: 5d pop rbp
; X64-NEXT:    22d: c3 ret
; X64-NEXT:    22e: 66 90 nop
;
; ARM64-LABEL: <switch_i32_noreuse>:
; ARM64:         stp x29, x30, [sp, #-0xa0]!
; ARM64-NEXT:    mov x29, sp
; ARM64-NEXT:    str x19, [sp, #0x10]
; ARM64-NEXT:    mov w19, w0
; ARM64-NEXT:    mov w0, w19
; ARM64-NEXT:    cmp w0, #0x1
; ARM64-NEXT:    b.eq 0x1dc <switch_i32_noreuse+0x2c>
; ARM64-NEXT:    cmp w0, #0x2
; ARM64-NEXT:    b.eq 0x1e4 <switch_i32_noreuse+0x34>
; ARM64-NEXT:    b 0x1d8 <switch_i32_noreuse+0x28>
; ARM64-NEXT:    b 0x1ec <switch_i32_noreuse+0x3c>
; ARM64-NEXT:    mov x0, #0x1 // =1
; ARM64-NEXT:    b 0x1f0 <switch_i32_noreuse+0x40>
; ARM64-NEXT:    mov x0, #0x2 // =2
; ARM64-NEXT:    b 0x1f0 <switch_i32_noreuse+0x40>
; ARM64-NEXT:    mov w0, w19
; ARM64-NEXT:    ldr x19, [sp, #0x10]
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
  switch i32 %p, label %default [
    i32 1, label %l1
    i32 2, label %l2
  ]
l1:
  ret i32 1
l2:
  ret i32 2
default:
  ret i32 %p
}

define i64 @switch_i64_noreuse(i64 %p) {
; X64-LABEL: <switch_i64_noreuse>:
; X64:         230: 55 push rbp
; X64-NEXT:    231: 48 89 e5 mov rbp, rsp
; X64-NEXT:    234: 53 push rbx
; X64-NEXT:    235: 48 89 fb mov rbx, rdi
; X64-NEXT:    238: 48 89 d8 mov rax, rbx
; X64-NEXT:    23b: 48 83 f8 01 cmp rax, 0x1
; X64-NEXT:    23f: 0f 84 14 00 00 00 je <L0>
; X64-NEXT:    245: 48 83 f8 02 cmp rax, 0x2
; X64-NEXT:    249: 0f 84 14 00 00 00 je <L1>
; X64-NEXT:    24f: e9 00 00 00 00 jmp <L2>
; X64-NEXT:  <L2>:
; X64-NEXT:    254: e9 14 00 00 00 jmp <L3>
; X64-NEXT:  <L0>:
; X64-NEXT:    259: b8 01 00 00 00 mov eax, 0x1
; X64-NEXT:    25e: e9 0d 00 00 00 jmp <L4>
; X64-NEXT:  <L1>:
; X64-NEXT:    263: b8 02 00 00 00 mov eax, 0x2
; X64-NEXT:    268: e9 03 00 00 00 jmp <L4>
; X64-NEXT:  <L3>:
; X64-NEXT:    26d: 48 89 d8 mov rax, rbx
; X64-NEXT:  <L4>:
; X64-NEXT:    270: 5b pop rbx
; X64-NEXT:    271: 5d pop rbp
; X64-NEXT:    272: c3 ret
; X64-NEXT:    273: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    27c: 0f 1f 40 00 nop dword ptr [rax]
;
; ARM64-LABEL: <switch_i64_noreuse>:
; ARM64:         stp x29, x30, [sp, #-0xa0]!
; ARM64-NEXT:    mov x29, sp
; ARM64-NEXT:    str x19, [sp, #0x10]
; ARM64-NEXT:    mov x19, x0
; ARM64-NEXT:    mov x0, x19
; ARM64-NEXT:    cmp x0, #0x1
; ARM64-NEXT:    b.eq 0x22c <switch_i64_noreuse+0x2c>
; ARM64-NEXT:    cmp x0, #0x2
; ARM64-NEXT:    b.eq 0x234 <switch_i64_noreuse+0x34>
; ARM64-NEXT:    b 0x228 <switch_i64_noreuse+0x28>
; ARM64-NEXT:    b 0x23c <switch_i64_noreuse+0x3c>
; ARM64-NEXT:    mov x0, #0x1 // =1
; ARM64-NEXT:    b 0x240 <switch_i64_noreuse+0x40>
; ARM64-NEXT:    mov x0, #0x2 // =2
; ARM64-NEXT:    b 0x240 <switch_i64_noreuse+0x40>
; ARM64-NEXT:    mov x0, x19
; ARM64-NEXT:    ldr x19, [sp, #0x10]
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
  switch i64 %p, label %default [
    i64 1, label %l1
    i64 2, label %l2
  ]
l1:
  ret i64 1
l2:
  ret i64 2
default:
  ret i64 %p
}

define i32 @switch_to_self() {
; X64-LABEL: <switch_to_self>:
; X64:         280: 31 c0 xor eax, eax
; X64-NEXT:    282: 83 f8 35 cmp eax, 0x35
; X64-NEXT:    285: 0f 84 34 01 00 00 je <L0>
; X64-NEXT:    28b: 0f 87 d7 00 00 00 ja <L1>
; X64-NEXT:    291: 83 f8 0a cmp eax, 0xa
; X64-NEXT:    294: 0f 82 0b 01 00 00 jb <L2>
; X64-NEXT:    29a: 83 f8 34 cmp eax, 0x34
; X64-NEXT:    29d: 0f 87 02 01 00 00 ja <L2>
; X64-NEXT:    2a3: 89 c0 mov eax, eax
; X64-NEXT:    2a5: 48 83 e8 0a sub rax, 0xa
; X64-NEXT:    2a9: 48 8d 0d 0c 00 00 00 lea rcx, <switch_to_self+0x3c>
; X64-NEXT:    2b0: 48 63 04 81 movsxd rax, dword ptr [rcx + 4*rax]
; X64-NEXT:    2b4: 48 01 c1 add rcx, rax
; X64-NEXT:    2b7: ff e1 jmp rcx
; X64-NEXT:    2b9: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    2bc: c4 ff ff <unknown>
; X64-NEXT:    2bf: ff e9 <unknown>
; X64-NEXT:    2c1: 00 00 add byte ptr [rax], al
; X64-NEXT:    2c3: 00 e9 add cl, ch
; X64-NEXT:    2c5: 00 00 add byte ptr [rax], al
; X64-NEXT:    2c7: 00 e9 add cl, ch
; X64-NEXT:    2c9: 00 00 add byte ptr [rax], al
; X64-NEXT:    2cb: 00 e9 add cl, ch
; X64-NEXT:    2cd: 00 00 add byte ptr [rax], al
; X64-NEXT:    2cf: 00 e9 add cl, ch
; X64-NEXT:    2d1: 00 00 add byte ptr [rax], al
; X64-NEXT:    2d3: 00 e9 add cl, ch
; X64-NEXT:    2d5: 00 00 add byte ptr [rax], al
; X64-NEXT:    2d7: 00 e9 add cl, ch
; X64-NEXT:    2d9: 00 00 add byte ptr [rax], al
; X64-NEXT:    2db: 00 e9 add cl, ch
; X64-NEXT:    2dd: 00 00 add byte ptr [rax], al
; X64-NEXT:    2df: 00 e9 add cl, ch
; X64-NEXT:    2e1: 00 00 add byte ptr [rax], al
; X64-NEXT:    2e3: 00 e9 add cl, ch
; X64-NEXT:    2e5: 00 00 add byte ptr [rax], al
; X64-NEXT:    2e7: 00 e9 add cl, ch
; X64-NEXT:    2e9: 00 00 add byte ptr [rax], al
; X64-NEXT:    2eb: 00 e9 add cl, ch
; X64-NEXT:    2ed: 00 00 add byte ptr [rax], al
; X64-NEXT:    2ef: 00 e9 add cl, ch
; X64-NEXT:    2f1: 00 00 add byte ptr [rax], al
; X64-NEXT:    2f3: 00 e9 add cl, ch
; X64-NEXT:    2f5: 00 00 add byte ptr [rax], al
; X64-NEXT:    2f7: 00 e9 add cl, ch
; X64-NEXT:    2f9: 00 00 add byte ptr [rax], al
; X64-NEXT:    2fb: 00 e9 add cl, ch
; X64-NEXT:    2fd: 00 00 add byte ptr [rax], al
; X64-NEXT:    2ff: 00 e9 add cl, ch
; X64-NEXT:    301: 00 00 add byte ptr [rax], al
; X64-NEXT:    303: 00 e9 add cl, ch
; X64-NEXT:    305: 00 00 add byte ptr [rax], al
; X64-NEXT:    307: 00 e9 add cl, ch
; X64-NEXT:    309: 00 00 add byte ptr [rax], al
; X64-NEXT:    30b: 00 e9 add cl, ch
; X64-NEXT:    30d: 00 00 add byte ptr [rax], al
; X64-NEXT:    30f: 00 e9 add cl, ch
; X64-NEXT:    311: 00 00 add byte ptr [rax], al
; X64-NEXT:    313: 00 e9 add cl, ch
; X64-NEXT:    315: 00 00 add byte ptr [rax], al
; X64-NEXT:    317: 00 e9 add cl, ch
; X64-NEXT:    319: 00 00 add byte ptr [rax], al
; X64-NEXT:    31b: 00 e9 add cl, ch
; X64-NEXT:    31d: 00 00 add byte ptr [rax], al
; X64-NEXT:    31f: 00 e9 add cl, ch
; X64-NEXT:    321: 00 00 add byte ptr [rax], al
; X64-NEXT:    323: 00 e9 add cl, ch
; X64-NEXT:    325: 00 00 add byte ptr [rax], al
; X64-NEXT:    327: 00 e9 add cl, ch
; X64-NEXT:    329: 00 00 add byte ptr [rax], al
; X64-NEXT:    32b: 00 e9 add cl, ch
; X64-NEXT:    32d: 00 00 add byte ptr [rax], al
; X64-NEXT:    32f: 00 e9 add cl, ch
; X64-NEXT:    331: 00 00 add byte ptr [rax], al
; X64-NEXT:    333: 00 e9 add cl, ch
; X64-NEXT:    335: 00 00 add byte ptr [rax], al
; X64-NEXT:    337: 00 e9 add cl, ch
; X64-NEXT:    339: 00 00 add byte ptr [rax], al
; X64-NEXT:    33b: 00 e9 add cl, ch
; X64-NEXT:    33d: 00 00 add byte ptr [rax], al
; X64-NEXT:    33f: 00 e9 add cl, ch
; X64-NEXT:    341: 00 00 add byte ptr [rax], al
; X64-NEXT:    343: 00 e9 add cl, ch
; X64-NEXT:    345: 00 00 add byte ptr [rax], al
; X64-NEXT:    347: 00 e9 add cl, ch
; X64-NEXT:    349: 00 00 add byte ptr [rax], al
; X64-NEXT:    34b: 00 e9 add cl, ch
; X64-NEXT:    34d: 00 00 add byte ptr [rax], al
; X64-NEXT:    34f: 00 e9 add cl, ch
; X64-NEXT:    351: 00 00 add byte ptr [rax], al
; X64-NEXT:    353: 00 03 add byte ptr [rbx], al
; X64-NEXT:    355: 01 00 add dword ptr [rax], eax
; X64-NEXT:    357: 00 03 add byte ptr [rbx], al
; X64-NEXT:    359: 01 00 add dword ptr [rax], eax
; X64-NEXT:    35b: 00 03 add byte ptr [rbx], al
; X64-NEXT:    35d: 01 00 add dword ptr [rax], eax
; X64-NEXT:    35f: 00 03 add byte ptr [rbx], al
; X64-NEXT:    361: 01 00 add dword ptr [rax], eax
; X64-NEXT:    363: 00 03 add byte ptr [rbx], al
; X64-NEXT:    365: 01 00 add dword ptr [rax], eax
; X64-NEXT:    367: 00 83 f8 62 0f 84 add byte ptr [rbx - 0x7bf09d08], al
; X64-NEXT:    36d: 40 00 00 add byte ptr [rax], al
; X64-NEXT:    370: 00 0f add byte ptr [rdi], cl
; X64-NEXT:    372: 87 17 xchg dword ptr [rdi], edx
; X64-NEXT:    374: 00 00 add byte ptr [rax], al
; X64-NEXT:    376: 00 83 f8 36 0f 84 add byte ptr [rbx - 0x7bf0c908], al
; X64-NEXT:    37c: 3f <unknown>
; X64-NEXT:    37d: 00 00 add byte ptr [rax], al
; X64-NEXT:    37f: 00 83 f8 37 0f 84 add byte ptr [rbx - 0x7bf0c808], al
; X64-NEXT:    385: 36 00 00 add byte ptr ss:[rax], al
; X64-NEXT:    388: 00 e9 add cl, ch
; X64-NEXT:    38a: 17 <unknown>
; X64-NEXT:    38b: 00 00 add byte ptr [rax], al
; X64-NEXT:    38d: 00 83 f8 66 0f 84 add byte ptr [rbx - 0x7bf09908], al
; X64-NEXT:    393: 21 00 and dword ptr [rax], eax
; X64-NEXT:    395: 00 00 add byte ptr [rax], al
; X64-NEXT:    397: 83 f8 72 cmp eax, 0x72
; X64-NEXT:    39a: 0f 84 0a 00 00 00 je <L3>
; X64-NEXT:    3a0: e9 00 00 00 00 jmp <L2>
; X64-NEXT:  <L2>:
; X64-NEXT:    3a5: e9 15 00 00 00 jmp <L0>
; X64-NEXT:  <L3>:
; X64-NEXT:    3aa: 31 c0 xor eax, eax
; X64-NEXT:    3ac: e9 10 00 00 00 jmp <L4>
; X64-NEXT:    3b1: 31 c0 xor eax, eax
; X64-NEXT:    3b3: e9 09 00 00 00 jmp <L4>
; X64-NEXT:    3b8: 31 c0 xor eax, eax
; X64-NEXT:    3ba: e9 02 00 00 00 jmp <L4>
; X64-NEXT:  <L0>:
; X64-NEXT:    3bf: 31 c0 xor eax, eax
; X64-NEXT:  <L4>:
; X64-NEXT:    3c1: c3 ret
;
; ARM64-LABEL: <switch_to_self>:
; ARM64:         mov w0, #0x0 // =0
; ARM64-NEXT:    cmp w0, #0x35
; ARM64-NEXT:    b.eq 0x380 <switch_to_self+0x130>
; ARM64-NEXT:    b.hi 0x330 <switch_to_self+0xe0>
; ARM64-NEXT:    cmp w0, #0xa
; ARM64-NEXT:    b.lo 0x364 <switch_to_self+0x114>
; ARM64-NEXT:    cmp w0, #0x34
; ARM64-NEXT:    b.hi 0x364 <switch_to_self+0x114>
; ARM64-NEXT:    sub x0, x0, #0xa
; ARM64-NEXT:    adr x1, 0x284 <switch_to_self+0x34>
; ARM64-NEXT:    ldrsw x0, [x1, w0, uxtw #2]
; ARM64-NEXT:    add x1, x1, x0
; ARM64-NEXT:    br x1
; ARM64-NEXT:    <unknown>
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xe0
; ARM64-NEXT:    udf #0xfc
; ARM64-NEXT:    udf #0xfc
; ARM64-NEXT:    udf #0xfc
; ARM64-NEXT:    udf #0xfc
; ARM64-NEXT:    udf #0xfc
; ARM64-NEXT:    cmp w0, #0x62
; ARM64-NEXT:    b.eq 0x370 <switch_to_self+0x120>
; ARM64-NEXT:    b.hi 0x350 <switch_to_self+0x100>
; ARM64-NEXT:    cmp w0, #0x36
; ARM64-NEXT:    b.eq 0x380 <switch_to_self+0x130>
; ARM64-NEXT:    cmp w0, #0x37
; ARM64-NEXT:    b.eq 0x380 <switch_to_self+0x130>
; ARM64-NEXT:    b 0x364 <switch_to_self+0x114>
; ARM64-NEXT:    cmp w0, #0x66
; ARM64-NEXT:    b.eq 0x378 <switch_to_self+0x128>
; ARM64-NEXT:    cmp w0, #0x72
; ARM64-NEXT:    b.eq 0x368 <switch_to_self+0x118>
; ARM64-NEXT:    b 0x364 <switch_to_self+0x114>
; ARM64-NEXT:    b 0x380 <switch_to_self+0x130>
; ARM64-NEXT:    mov w0, #0x0 // =0
; ARM64-NEXT:    b 0x384 <switch_to_self+0x134>
; ARM64-NEXT:    mov w0, #0x0 // =0
; ARM64-NEXT:    b 0x384 <switch_to_self+0x134>
; ARM64-NEXT:    mov w0, #0x0 // =0
; ARM64-NEXT:    b 0x384 <switch_to_self+0x134>
; ARM64-NEXT:    mov w0, #0x0 // =0
; ARM64-NEXT:    ret
  br label %1

1:
  switch i32 0, label %5 [
    i32 55, label %5
    i32 114, label %2
    i32 54, label %5
    i32 98, label %3
    i32 102, label %4
    i32 10, label %1
    i32 48, label %5
    i32 49, label %5
    i32 50, label %5
    i32 51, label %5
    i32 52, label %5
    i32 53, label %5
  ]

2:
  ret i32 0

3:
  ret i32 0

4:
  ret i32 0

5:
  ret i32 0
}
